export const MANHATTAN_ISLAND = {
  type: "Feature",
  properties: { name: "Manhattan" },
  geometry: {
    type: "Polygon",
    coordinates: [
      [
        [-74.0196, 40.7002],
        [-74.0178, 40.7098],
        [-74.0149, 40.7198],
        [-74.0127, 40.7302],
        [-74.0105, 40.7406],
        [-74.0084, 40.7509],
        [-74.0061, 40.7615],
        [-74.0028, 40.7724],
        [-73.9988, 40.7835],
        [-73.9938, 40.7943],
        [-73.9883, 40.8047],
        [-73.9819, 40.8155],
        [-73.9736, 40.8288],
        [-73.9657, 40.8422],
        [-73.9583, 40.8554],
        [-73.9519, 40.8706],
        [-73.9412, 40.8778],
        [-73.9312, 40.8734],
        [-73.9362, 40.8598],
        [-73.9414, 40.8465],
        [-73.9468, 40.8334],
        [-73.9526, 40.8202],
        [-73.9588, 40.8068],
        [-73.9653, 40.7936],
        [-73.9709, 40.7802],
        [-73.9756, 40.7663],
        [-73.9799, 40.7523],
        [-73.9846, 40.7384],
        [-73.9898, 40.7241],
        [-73.9961, 40.7113],
        [-74.0039, 40.7026],
        [-74.0126, 40.6996],
        [-74.0196, 40.7002],
      ],
    ],
  },
};

export const MANHATTAN_STREET_SEGMENTS = [
  {
    id: "broadway-financial-district",
    corridor: "Broadway Corridor",
    currentName: "Broadway",
    segmentLabel: "Battery to City Hall",
    bounds: "Bowling Green to City Hall Park",
    altNames: ["The Great White Way (nickname, especially in Midtown)"],
    formerNames: [
      "Heere Straat",
      "Great George Street",
      "The Boulevard",
      "Boulevard Lafayette",
      "Eleventh Avenue",
      "Kingsbridge Road",
      "Breede weg (Dutch, \"broad road\")",
    ],
    origin:
      "Broadway was likely built on an older Native trail and became known for being wider than surrounding lower-Manhattan streets. Across eras it carried multiple names before a single official naming was applied to the full Manhattan length in 1899.",
    timeline: [
      "Pre-colonial era: probable Native travel path alignment.",
      "17th-19th centuries: multiple names used in different stretches and periods.",
      "1899: full 15.5-mile Manhattan route legally unified as Broadway.",
    ],
    confidence: "high",
    sources: [
      { label: "NYC Parks - Broadway Malls", url: "https://www.nycgovparks.org/parks/broadway-malls/history" },
      { label: "Wikipedia - Broadway (Manhattan)", url: "https://en.wikipedia.org/wiki/Broadway_(Manhattan)" },
      { label: "The Street Book (Henry Moscow)" },
    ],
    coordinates: [
      [-74.0121, 40.7047],
      [-74.0088, 40.7125],
      [-74.0056, 40.7212],
      [-74.0019, 40.7301],
    ],
  },
  {
    id: "broadway-midtown",
    corridor: "Broadway Corridor",
    currentName: "Broadway",
    segmentLabel: "Union Square to Columbus Circle",
    bounds: "Union Square to Columbus Circle",
    altNames: ["The Great White Way (theater district nickname)"],
    formerNames: [],
    origin:
      "The Midtown segment became globally known for its theater corridor, earning the nickname 'The Great White Way' due to bright electric signs.",
    timeline: [
      "Late 1800s to early 1900s: Theater concentration accelerates.",
      "Early 1900s: Nickname 'The Great White Way' popularized.",
    ],
    confidence: "medium",
    sources: [
      { label: "Britannica - Broadway", url: "https://www.britannica.com/topic/Broadway-theatre-district-New-York-City-New-York" },
      { label: "Wikipedia - Broadway Theater", url: "https://en.wikipedia.org/wiki/Broadway_theatre" },
    ],
    coordinates: [
      [-73.9901, 40.7363],
      [-73.9868, 40.7451],
      [-73.983, 40.7556],
      [-73.98, 40.7658],
      [-73.9776, 40.7746],
    ],
  },
  {
    id: "sixth-ave-village",
    corridor: "Avenue of the Americas / 6th Ave",
    currentName: "Avenue of the Americas",
    segmentLabel: "SoHo / Greenwich Village section",
    bounds: "Canal St to 14th St",
    altNames: ["Sixth Avenue", "6th Ave"],
    formerNames: ["Sixth Avenue"],
    origin:
      "The avenue was officially renamed Avenue of the Americas in 1945 to promote Pan-American unity, but many New Yorkers still use 'Sixth Avenue' in speech.",
    timeline: [
      "Before 1945: Sixth Avenue.",
      "1945: Officially renamed Avenue of the Americas.",
      "Present: Dual usage remains common.",
    ],
    confidence: "high",
    sources: [
      { label: "NYC Department of City Planning references", url: "https://www.nyc.gov/site/planning/" },
      { label: "Wikipedia - Sixth Avenue", url: "https://en.wikipedia.org/wiki/Sixth_Avenue" },
      { label: "The Street Book (Henry Moscow), p. 28" },
    ],
    coordinates: [
      [-74.0095, 40.7211],
      [-74.0066, 40.7293],
      [-74.0023, 40.7382],
    ],
  },
  {
    id: "sixth-ave-midtown",
    corridor: "Avenue of the Americas / 6th Ave",
    currentName: "Avenue of the Americas",
    segmentLabel: "Midtown section",
    bounds: "14th St to Central Park South",
    altNames: ["Sixth Avenue", "6th Ave"],
    formerNames: ["Sixth Avenue"],
    origin:
      "Even on official maps and signs, the avenue often displays both naming traditions: ceremonial naming plus numeric avenue identity.",
    timeline: [
      "1945 onward: Avenue of the Americas (official).",
      "Continuous colloquial use: Sixth Avenue.",
    ],
    confidence: "medium",
    sources: [
      { label: "NYC signage practices overview", url: "https://www.nyc.gov/" },
      { label: "Wikipedia - Sixth Avenue", url: "https://en.wikipedia.org/wiki/Sixth_Avenue" },
      { label: "The Street Book (Henry Moscow), p. 28" },
    ],
    coordinates: [
      [-74.0023, 40.7382],
      [-73.9972, 40.7484],
      [-73.9933, 40.759],
      [-73.9894, 40.7697],
      [-73.9858, 40.7802],
    ],
  },
  {
    id: "bowery-lower",
    corridor: "Bowery / 4th Ave / Park Ave Corridor",
    currentName: "Bowery",
    segmentLabel: "Chatham Square to Cooper Square",
    bounds: "Chatham Square to Cooper Square",
    altNames: [],
    formerNames: ["Bouwerij road (Dutch farm road root)"],
    origin:
      "Bowery derives from Dutch 'bouwerij' (farm) and referred to the route toward Peter Stuyvesant's farm from settled New Amsterdam. By the late 18th century it was fashionable; by the Civil War era it had a much rougher reputation.",
    timeline: [
      "1600s: Farm road associated with Dutch bouwerij lands.",
      "Late 1700s: Bowery regarded as one of the city's elegant streets.",
      "Civil War era: social decline and flophouse association grows.",
      "1700s onward: Name evolves to Bowery.",
    ],
    confidence: "high",
    sources: [
      { label: "Wikipedia - Bowery", url: "https://en.wikipedia.org/wiki/Bowery" },
      { label: "NYC neighborhood history resources", url: "https://www.nyc.gov/" },
      { label: "The Street Book (Henry Moscow)" },
    ],
    coordinates: [
      [-73.9967, 40.7114],
      [-73.9939, 40.7182],
      [-73.9908, 40.7249],
      [-73.9878, 40.7296],
    ],
  },
  {
    id: "fourth-ave-union",
    corridor: "Bowery / 4th Ave / Park Ave Corridor",
    currentName: "Fourth Avenue",
    segmentLabel: "Cooper Square to Union Square",
    bounds: "Astor Place area to Union Square",
    altNames: [],
    formerNames: [],
    origin:
      "This short section carries the numbered avenue scheme before the same northbound alignment transitions into Park Avenue South.",
    timeline: [
      "19th century grid era: Standard numbered avenue naming.",
      "At 14th Street: Name changes to Park Avenue South.",
    ],
    confidence: "medium",
    sources: [
      { label: "Wikipedia - Fourth Avenue (Manhattan)", url: "https://en.wikipedia.org/wiki/Fourth_Avenue_(Manhattan)" },
    ],
    coordinates: [
      [-73.9878, 40.7296],
      [-73.9851, 40.7361],
      [-73.9826, 40.7422],
    ],
  },
  {
    id: "park-ave-south",
    corridor: "Bowery / 4th Ave / Park Ave Corridor",
    currentName: "Park Avenue South",
    segmentLabel: "Union Square to Grand Central area",
    bounds: "14th St to 32nd St",
    altNames: ["Fourth Avenue (historic continuity)"],
    formerNames: [],
    origin:
      "As the corridor moved uptown and urban design changed, this stretch adopted the Park Avenue South name while remaining part of the same traffic spine.",
    timeline: [
      "After 14th Street: corridor renamed Park Avenue South.",
      "Northbound continuity persists into Park Avenue.",
    ],
    confidence: "medium",
    sources: [
      { label: "Wikipedia - Park Avenue", url: "https://en.wikipedia.org/wiki/Park_Avenue" },
    ],
    coordinates: [
      [-73.9826, 40.7422],
      [-73.98, 40.7487],
      [-73.9777, 40.7553],
      [-73.9758, 40.7617],
      [-73.9744, 40.7685],
    ],
  },
  {
    id: "park-ave-upper",
    corridor: "Bowery / 4th Ave / Park Ave Corridor",
    currentName: "Park Avenue",
    segmentLabel: "Midtown to Upper Manhattan",
    bounds: "32nd St to Harlem River area",
    altNames: [],
    formerNames: ["Fourth Avenue (historic name, earlier period)"],
    origin:
      "The boulevard became associated with landscaped medians and rail improvements, helping cement the Park Avenue identity.",
    timeline: [
      "19th century: Fourth Avenue naming in use.",
      "Late 19th century onward: Park Avenue identity solidifies.",
    ],
    confidence: "medium",
    sources: [
      { label: "Wikipedia - Park Avenue", url: "https://en.wikipedia.org/wiki/Park_Avenue" },
      { label: "NYC Landmarks and neighborhood histories", url: "https://www.nyc.gov/site/lpc/" },
    ],
    coordinates: [
      [-73.9744, 40.7685],
      [-73.9728, 40.7765],
      [-73.9712, 40.7859],
      [-73.9695, 40.7967],
      [-73.9668, 40.8092],
      [-73.9639, 40.8226],
      [-73.9609, 40.8362],
      [-73.9579, 40.8502],
      [-73.9547, 40.8638],
    ],
  },
  {
    id: "malcolmx-lenox",
    corridor: "Lenox / Malcolm X Corridor",
    currentName: "Malcolm X Boulevard",
    segmentLabel: "Central Harlem section",
    bounds: "110th St to 147th St corridor",
    altNames: ["Lenox Avenue"],
    formerNames: ["Lenox Avenue (still used for parts and in older references)"],
    origin:
      "Portions were ceremonially renamed Malcolm X Boulevard in the late 20th century, reflecting neighborhood identity and civil rights memory.",
    timeline: [
      "Earlier usage: Lenox Avenue.",
      "1987: Malcolm X Boulevard naming adopted for significant stretches.",
      "Present: both names appear depending on segment/signage context.",
    ],
    confidence: "high",
    sources: [
      { label: "Wikipedia - Malcolm X Boulevard", url: "https://en.wikipedia.org/wiki/Malcolm_X_Boulevard" },
      { label: "Wikipedia - Lenox Avenue", url: "https://en.wikipedia.org/wiki/Lenox_Avenue" },
    ],
    coordinates: [
      [-73.9504, 40.7935],
      [-73.9488, 40.8024],
      [-73.947, 40.8117],
      [-73.9451, 40.8214],
      [-73.9433, 40.8313],
      [-73.9415, 40.8413],
      [-73.9398, 40.8516],
      [-73.9382, 40.8615],
    ],
  },
  {
    id: "adam-clayton-powell",
    corridor: "Seventh Avenue Corridor",
    currentName: "Adam Clayton Powell Jr. Boulevard",
    segmentLabel: "Harlem segment (co-named Seventh Avenue)",
    bounds: "Harlem, north of Central Park",
    altNames: ["Seventh Avenue"],
    formerNames: ["Seventh Avenue (Harlem portion)"],
    origin:
      "Named for Adam Clayton Powell Jr., the 11-term Congressman from Harlem and pastor of Abyssinian Baptist Church. A major civil rights leader, he was first elected to Congress in 1944. The Harlem stretch of Seventh Avenue was named for him shortly after his death in 1972.",
    timeline: [
      "Original avenue grid: Seventh Avenue.",
      "1944: Powell elected to Congress.",
      "1972: Boulevard naming adopted after Powell's death.",
    ],
    confidence: "high",
    sources: [
      { label: "The Street Book (Henry Moscow), p. 24" },
      { label: "Wikipedia - Adam Clayton Powell Jr. Boulevard", url: "https://en.wikipedia.org/wiki/Adam_Clayton_Powell_Jr._Boulevard" },
    ],
    coordinates: [
      [-73.9803, 40.7536],
      [-73.9771, 40.7636],
      [-73.9737, 40.7741],
      [-73.9699, 40.7848],
      [-73.9658, 40.7958],
      [-73.9614, 40.8069],
      [-73.9566, 40.8182],
      [-73.9515, 40.8294],
      [-73.946, 40.8408],
      [-73.9405, 40.8521],
    ],
  },
  {
    id: "fdr-drive",
    corridor: "East Side Arterial",
    currentName: "FDR Drive",
    segmentLabel: "East River waterfront",
    bounds: "Battery Park area to Harlem River",
    altNames: ["East River Drive", "Franklin D. Roosevelt Drive"],
    formerNames: ["East River Drive"],
    origin:
      "Originally known as East River Drive, the route was built in stages beginning in the 1930s and later renamed for President Franklin D. Roosevelt.",
    timeline: [
      "1936: Initial section planning/launch under borough and city leadership.",
      "1940: Early section dedication (Grand St to 60th St corridor context).",
      "Later period: corridor widely referenced as FDR Drive.",
    ],
    confidence: "high",
    sources: [
      { label: "Wikipedia - FDR Drive", url: "https://en.wikipedia.org/wiki/FDR_Drive" },
      { label: "NYC DOT references", url: "https://www.nyc.gov/html/dot/" },
    ],
    coordinates: [
      [-73.9722, 40.7042],
      [-73.9719, 40.7151],
      [-73.9708, 40.7266],
      [-73.9691, 40.7384],
      [-73.9666, 40.7502],
      [-73.9636, 40.7626],
      [-73.9601, 40.7746],
      [-73.9563, 40.7871],
      [-73.9522, 40.7995],
      [-73.9478, 40.8126],
      [-73.9433, 40.8265],
      [-73.9382, 40.8412],
      [-73.9328, 40.8562],
      [-73.9279, 40.8694],
    ],
  },
  {
    id: "west-side-highway",
    corridor: "West Side Arterial",
    currentName: "West Side Highway",
    segmentLabel: "Hudson River waterfront",
    bounds: "Battery Place to upper Manhattan",
    altNames: ["Joe DiMaggio Highway", "Route 9A (parts)"],
    formerNames: ["Miller Highway (older elevated sections)"],
    origin:
      "The corridor has carried multiple names over time, including commemorative and route-designation labels layered onto the same north-south waterfront path.",
    timeline: [
      "Earlier era: Miller Highway for elevated segments.",
      "Modern era: West Side Highway.",
      "Commemorative co-name: Joe DiMaggio Highway.",
    ],
    confidence: "medium",
    sources: [
      { label: "Wikipedia - West Side Highway", url: "https://en.wikipedia.org/wiki/West_Side_Highway" },
      { label: "NYC DOT arterial history resources", url: "https://www.nyc.gov/html/dot/" },
    ],
    coordinates: [
      [-74.0159, 40.7047],
      [-74.0144, 40.716],
      [-74.0128, 40.7276],
      [-74.0114, 40.7396],
      [-74.0098, 40.7518],
      [-74.0083, 40.7643],
      [-74.0068, 40.7765],
      [-74.0052, 40.7891],
      [-74.0036, 40.8022],
      [-74.0016, 40.8157],
      [-73.9994, 40.8299],
      [-73.9969, 40.8449],
      [-73.9942, 40.8598],
      [-73.9916, 40.8726],
    ],
  },
  {
    id: "canal-street",
    corridor: "Historic Waterway Streets",
    currentName: "Canal Street",
    segmentLabel: "Lower Manhattan crosstown",
    bounds: "Hudson-side approaches to East Side approaches",
    altNames: [],
    formerNames: [],
    origin:
      "Canal Street traces the line of a former canal built over the old Collect Pond drainage corridor in the early 19th century.",
    timeline: [
      "Early 1800s: Canal built to drain the Collect Pond area.",
      "Later: Waterway filled, roadway remains as Canal Street.",
    ],
    confidence: "high",
    sources: [
      { label: "Wikipedia - Canal Street (Manhattan)", url: "https://en.wikipedia.org/wiki/Canal_Street_(Manhattan)" },
      { label: "NYC historical maps references", url: "https://www.nypl.org/" },
    ],
    coordinates: [
      [-74.0107, 40.7186],
      [-74.0021, 40.7186],
      [-73.9935, 40.7187],
      [-73.9852, 40.7187],
      [-73.9767, 40.7188],
    ],
  },
  {
    id: "houston-street",
    corridor: "Historic Waterway Streets",
    currentName: "Houston Street",
    segmentLabel: "West Village to Lower East Side",
    bounds: "West Side to East Side crosstown corridor",
    altNames: ["Pronounced 'HOW-ston' (not like Houston, Texas)"],
    formerNames: [],
    origin:
      "Named after William Houstoun (a Georgia statesman), producing the local pronunciation 'HOW-ston' that differs from Houston, Texas.",
    timeline: [
      "Early naming: after William Houstoun family context.",
      "Present: distinctive NYC pronunciation remains in common use.",
    ],
    confidence: "medium",
    sources: [
      { label: "Wikipedia - Houston Street", url: "https://en.wikipedia.org/wiki/Houston_Street" },
      { label: "NYC historical pronunciation notes", url: "https://www.nypl.org/" },
      { label: "The Street Book (Henry Moscow)" },
    ],
    coordinates: [
      [-74.0085, 40.7287],
      [-73.9994, 40.7288],
      [-73.9903, 40.7288],
      [-73.9812, 40.7289],
      [-73.9721, 40.729],
    ],
  },
  {
    id: "east-river-drive",
    corridor: "East Side Arterial",
    currentName: "East River Drive",
    segmentLabel: "Historic first-section naming",
    bounds: "Grand Street to 60th Street (first section context)",
    altNames: ["Franklin D. Roosevelt Drive", "FDR Drive"],
    formerNames: [],
    origin:
      "Named for the river it parallels; initial sections were initiated in 1936 and a major early segment was dedicated in 1940, before the corridor became broadly known as FDR Drive.",
    timeline: ["1936: Initiation under city arterial-highway plans.", "1940: Early section dedication."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow)" }],
    coordinates: [
      [-73.9691, 40.7384],
      [-73.9666, 40.7502],
      [-73.9636, 40.7626],
      [-73.9601, 40.7746],
      [-73.9563, 40.7871],
    ],
  },
  {
    id: "wall-street",
    corridor: "Colonial-Era Streets",
    currentName: "Wall Street",
    segmentLabel: "Financial District core",
    bounds: "Broadway to South Street area",
    altNames: ["The Street (financial shorthand)"],
    formerNames: [],
    origin:
      "Named for the defensive wall built by Dutch colonists along the northern edge of New Amsterdam in the 17th century.",
    timeline: [
      "1650s: Defensive wall established.",
      "Later: Wall removed, street name remains.",
      "Modern era: Global financial symbolism.",
    ],
    confidence: "high",
    sources: [
      { label: "Federal Reserve history notes", url: "https://www.federalreservehistory.org/" },
      { label: "Wikipedia - Wall Street", url: "https://en.wikipedia.org/wiki/Wall_Street" },
    ],
    coordinates: [
      [-74.0103, 40.7073],
      [-74.0063, 40.7075],
      [-74.0025, 40.7077],
      [-73.9989, 40.7078],
    ],
  },
  {
    id: "abingdon-square",
    corridor: "Greenwich Village Squares",
    currentName: "Abingdon Square",
    segmentLabel: "Historic Village square block",
    bounds: "Bounded by Charles, Perry, Bleecker, and Tenth Streets",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Charlotte Warren, daughter of Admiral Sir Peter Warren, who married the Earl of Abingdon. Although many British-linked names were changed in 1794, Abingdon Square's name was retained.",
    timeline: ["1744: Warren land purchase.", "1794: Name retained during broader renaming efforts."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 24" }],
    coordinates: [
      [-74.0053, 40.7364],
      [-74.0038, 40.7368],
      [-74.0028, 40.7357],
      [-74.0043, 40.7352],
      [-74.0053, 40.7364],
    ],
  },
  {
    id: "academy-street",
    corridor: "Inwood Streets",
    currentName: "Academy Street",
    segmentLabel: "Dyckman / Inwood section",
    bounds: "Dyckman Street area (Inwood)",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Public School 52, a Tudor-style school building that once occupied a full block in the Inwood area before being demolished in 1957.",
    timeline: ["Pre-1957: Name tied to P.S. 52 context."],
    confidence: "medium",
    sources: [{ label: "The Street Book (Henry Moscow), p. 24" }],
    coordinates: [
      [-73.9315, 40.8673],
      [-73.9299, 40.868],
      [-73.9276, 40.869],
    ],
  },
  {
    id: "admiral-george-dewey-promenade",
    corridor: "Battery Park Waterfront",
    currentName: "Admiral George Dewey Promenade",
    segmentLabel: "Battery waterfront walk",
    bounds: "Harbor / Battery Park edge",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Admiral George Dewey, whose Manila Bay victory in 1898 made him a national hero. The promenade naming came later, in 1965.",
    timeline: ["1899: Hero's welcome in New York.", "1965: Promenade named in his honor."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 25" }],
    coordinates: [
      [-74.0175, 40.7044],
      [-74.0168, 40.7048],
      [-74.0158, 40.7051],
      [-74.0148, 40.7052],
    ],
  },
  {
    id: "albany-street",
    corridor: "Lower Manhattan Historic Streets",
    currentName: "Albany Street",
    segmentLabel: "Lower Manhattan segment",
    bounds: "Hudson River side toward Broadway (planned extension)",
    altNames: [],
    formerNames: [],
    origin:
      "Named for a Hudson-side pier built in 1797 serving New York-Albany traffic. A long 19th-century effort to extend the street through Trinity Churchyard was never carried out.",
    timeline: ["1797: Street tied to Albany-run pier.", "1850s: Extension controversy ends without completion."],
    confidence: "medium",
    sources: [{ label: "The Street Book (Henry Moscow), p. 25" }],
    coordinates: [
      [-74.0154, 40.7094],
      [-74.0128, 40.7095],
      [-74.0103, 40.7097],
    ],
  },
  {
    id: "alexander-hamilton-square",
    corridor: "Hamilton Heights Landmarks",
    currentName: "Alexander Hamilton Square",
    segmentLabel: "Near The Grange",
    bounds: "Hamilton Heights / St. Nicholas Park area",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Alexander Hamilton, Revolutionary officer and first U.S. Treasury Secretary. The square is associated with the area around his historic home, The Grange.",
    timeline: ["1800s onward: Square naming associated with Hamilton legacy."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 25" }],
    coordinates: [
      [-73.9498, 40.8226],
      [-73.9487, 40.8231],
      [-73.9476, 40.8235],
    ],
  },
  {
    id: "allen-street",
    corridor: "Lower East Side Corridors",
    currentName: "Allen Street",
    segmentLabel: "Lower East Side segment",
    bounds: "Lower East Side",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Captain William Henry Allen, a young U.S. Navy commander of the War of 1812 who died in action in 1813.",
    timeline: ["1813: Street naming linked to Captain Allen's death and public tribute."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 26" }],
    coordinates: [
      [-73.9924, 40.7149],
      [-73.9918, 40.7195],
      [-73.9911, 40.7246],
      [-73.9904, 40.7297],
    ],
  },
  {
    id: "amsterdam-avenue",
    corridor: "West Side Avenues",
    currentName: "Amsterdam Avenue",
    segmentLabel: "Above 59th Street",
    bounds: "Above 59th Street",
    altNames: ["Tenth Avenue (historic continuity)"],
    formerNames: ["Tenth Avenue (above 59th Street)"],
    origin:
      "Renamed in 1890 from the northern portion of Tenth Avenue. The name references Amsterdam and New York's Dutch settlement history; proponents also argued the change would improve neighborhood appeal and property values.",
    timeline: ["Before 1890: Tenth Avenue above 59th Street.", "1890: Officially renamed Amsterdam Avenue."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 26" }],
    coordinates: [
      [-73.9882, 40.7681],
      [-73.9845, 40.7795],
      [-73.9806, 40.7914],
      [-73.9766, 40.8036],
      [-73.9725, 40.8159],
      [-73.9685, 40.8284],
      [-73.9649, 40.8404],
      [-73.9612, 40.8529],
    ],
  },
  {
    id: "ann-street",
    corridor: "Lower Manhattan Historic Streets",
    currentName: "Ann Street",
    segmentLabel: "Downtown short street",
    bounds: "Downtown Manhattan",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Ann White, wife of merchant and developer Captain Thomas White, who subdivided land in the old governor's garden area.",
    timeline: ["18th century: Street established and named for Ann White."],
    confidence: "medium",
    sources: [{ label: "The Street Book (Henry Moscow), p. 26" }],
    coordinates: [
      [-74.0082, 40.7105],
      [-74.0066, 40.7108],
      [-74.0049, 40.711],
    ],
  },
  {
    id: "a-philip-randolph-square",
    corridor: "Harlem Civic Spaces",
    currentName: "A. Philip Randolph Square",
    segmentLabel: "Harlem memorial square",
    bounds: "Harlem area",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Asa Philip Randolph, founder of the Brotherhood of Sleeping Car Porters and a central Black labor and civil rights leader.",
    timeline: ["1925: Brotherhood of Sleeping Car Porters founded.", "1968: Randolph becomes president emeritus."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 26" }],
    coordinates: [
      [-73.9443, 40.8114],
      [-73.9437, 40.8119],
      [-73.9431, 40.8124],
    ],
  },
  {
    id: "arden-street",
    corridor: "Washington Heights Streets",
    currentName: "Arden Street",
    segmentLabel: "Washington Heights segment",
    bounds: "Washington Heights (between 170th and 176th Streets)",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Jacob Arden, butcher, property owner, and Revolutionary-era patriot active in anti-British protest and militia service.",
    timeline: ["Late 18th century: Jacob Arden's local prominence."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 27" }],
    coordinates: [
      [-73.9348, 40.8448],
      [-73.9333, 40.8457],
      [-73.9317, 40.8467],
    ],
  },
  {
    id: "asser-levy-place",
    corridor: "East Village Historic Streets",
    currentName: "Asser Levy Place",
    segmentLabel: "Stuyvesant Town / East Village edge",
    bounds: "Near 23rd Street and First Avenue area",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Asser Levy, one of the earliest Jewish settlers in New Amsterdam (1654), noted for resisting religious discrimination and for early kosher butchery in the city.",
    timeline: ["1654: Arrival in New Amsterdam.", "1954: Street named on tercentenary."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 27" }],
    coordinates: [
      [-73.9765, 40.7345],
      [-73.9762, 40.7361],
      [-73.9759, 40.7375],
    ],
  },
  {
    id: "astor-place",
    corridor: "NoHo / Astor Corridor",
    currentName: "Astor Place",
    segmentLabel: "NoHo segment",
    bounds: "Astor Place area",
    altNames: [],
    formerNames: [],
    origin:
      "Named for John Jacob Astor, the German-born merchant and real-estate magnate whose family was deeply linked to this neighborhood.",
    timeline: ["1783: Astor arrives in the U.S.", "1848: Astor dies."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 27" }],
    coordinates: [
      [-73.9926, 40.7297],
      [-73.9912, 40.7302],
      [-73.9899, 40.7308],
    ],
  },
  {
    id: "attorney-street",
    corridor: "Lower East Side Streets",
    currentName: "Attorney Street",
    segmentLabel: "LES north-south segment",
    bounds: "Lower East Side",
    altNames: [],
    formerNames: [],
    origin:
      "Likely named for one or more lawyers with offices in the vicinity; laid out before 1797, though the exact namesake remains uncertain.",
    timeline: ["Pre-1797: Street laid out."],
    confidence: "medium",
    sources: [{ label: "The Street Book (Henry Moscow), p. 27" }],
    coordinates: [
      [-73.9847, 40.7152],
      [-73.9838, 40.7203],
      [-73.983, 40.7254],
    ],
  },
  {
    id: "audubon-avenue",
    corridor: "Washington Heights Avenues",
    currentName: "Audubon Avenue",
    segmentLabel: "Upper Manhattan segment",
    bounds: "Washington Heights / old Audubon farm area",
    altNames: [],
    formerNames: [],
    origin:
      "Named for naturalist John James Audubon, who spent his final years in this part of upper Manhattan and died there in 1851.",
    timeline: ["Mid-19th century: Audubon residence period.", "1851: Audubon dies in New York."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 27" }],
    coordinates: [
      [-73.9322, 40.8434],
      [-73.9306, 40.8502],
      [-73.9288, 40.8576],
    ],
  },
  {
    id: "alphabet-city-avenues",
    corridor: "Alphabet City",
    currentName: "Avenues A, B, C and D",
    segmentLabel: "Alphabet City grid",
    bounds: "Eastward bulge of Manhattan, generally 14th Street and below",
    altNames: ["Alphabet City (colloquial)"],
    formerNames: [],
    origin:
      "The 1811 Commissioners' Plan used lettered avenues in Manhattan's far-east bulge, where extending the numbered avenue system would have produced awkward short fragments.",
    timeline: ["1811 onward: Lettered avenues formalized."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 27" }],
    coordinates: [
      [-73.9828, 40.7301],
      [-73.9799, 40.7267],
      [-73.9768, 40.7232],
      [-73.9738, 40.7197],
      [-73.9707, 40.7162],
    ],
  },
  {
    id: "avenue-of-the-finest",
    corridor: "Civic Center Corridors",
    currentName: "Avenue of the Finest",
    segmentLabel: "Police Plaza frontage",
    bounds: "Near City Hall / 1 Police Plaza",
    altNames: [],
    formerNames: [],
    origin:
      "Named in 1973 for the New York Police Department in conjunction with the opening of Police Headquarters at 1 Police Plaza.",
    timeline: ["1973: Naming tied to new NYPD headquarters opening."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 28" }],
    coordinates: [
      [-73.9979, 40.7128],
      [-73.9968, 40.7135],
      [-73.9957, 40.7142],
    ],
  },
  {
    id: "bache-plaza",
    corridor: "Financial District Plazas",
    currentName: "Bache Plaza",
    segmentLabel: "100 Gold Street vicinity",
    bounds: "Near 100 Gold Street",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Bache Halsey Stuart Shields, reflecting the lineage of brokerage firms including J.S. Bache & Company and financier Jules S. Bache.",
    timeline: ["1970s: Brokerage merger era.", "1861-1944: Jules Bache lifetime context."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 28" }],
    coordinates: [
      [-74.0038, 40.7106],
      [-74.0029, 40.7112],
      [-74.0021, 40.7118],
    ],
  },
  {
    id: "bank-street",
    corridor: "Greenwich Village Historic Streets",
    currentName: "Bank Street",
    segmentLabel: "West Village segment",
    bounds: "Greenwich Village",
    altNames: [],
    formerNames: [],
    origin:
      "Named for a Bank of New York branch built on the lane after a 1798 yellow fever scare in the Wall Street district prompted temporary relocation planning.",
    timeline: ["1798: Emergency branch context during yellow fever period.", "1822: Epidemic-era relevance reinforced."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 29" }],
    coordinates: [
      [-74.0066, 40.7365],
      [-74.0038, 40.7367],
      [-74.0012, 40.7368],
    ],
  },
  {
    id: "barclay-street",
    corridor: "Lower Manhattan Historic Streets",
    currentName: "Barclay Street",
    segmentLabel: "Tribeca / City Hall edge",
    bounds: "Lower Manhattan",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Reverend Henry Barclay, Trinity Church's second rector (from 1746), reflecting Trinity's major influence in lower Manhattan street naming.",
    timeline: ["1746: Barclay becomes Trinity rector."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 29" }],
    coordinates: [
      [-74.0117, 40.7126],
      [-74.0088, 40.7129],
      [-74.0059, 40.7132],
    ],
  },
  {
    id: "barrow-street",
    corridor: "West Village Historic Streets",
    currentName: "Barrow Street",
    segmentLabel: "West Village segment",
    bounds: "West Village",
    altNames: [],
    formerNames: ["Reason Street", "Raisin Street"],
    origin:
      "Originally Reason Street (linked to Thomas Paine's 'Age of Reason'), later popularly corrupted to Raisin Street; eventually renamed for artist Thomas Barrow.",
    timeline: ["1807: Thomas Barrow's Trinity Church print era.", "Early 19th century: Name transition from Reason/Raisin to Barrow."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 29" }],
    coordinates: [
      [-74.0066, 40.7316],
      [-74.0046, 40.7321],
      [-74.0028, 40.7326],
    ],
  },
  {
    id: "baruch-place-drive",
    corridor: "Lower East Side Civic Streets",
    currentName: "Baruch Place / Baruch Drive",
    segmentLabel: "LES civic corridor",
    bounds: "Lower East Side",
    altNames: [],
    formerNames: ["Goerck Street"],
    origin:
      "Renamed from Goerck Street in 1933 for Dr. Simon Baruch, physician and sanitation reform advocate, father of financier Bernard Baruch.",
    timeline: ["1933: Renamed from Goerck Street."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 29" }],
    coordinates: [
      [-73.9794, 40.7196],
      [-73.9782, 40.7211],
      [-73.9769, 40.7226],
    ],
  },
  {
    id: "battery-place",
    corridor: "Battery Historic Waterfront",
    currentName: "Battery Place",
    segmentLabel: "Battery Park edge",
    bounds: "Battery Park area",
    altNames: [],
    formerNames: [],
    origin:
      "Named for an artillery battery installed in 1693 as part of colonial defenses against a feared French attack; the site remained militarily important through the War of 1812.",
    timeline: ["1693: Artillery battery established.", "War of 1812 era: Continued strategic role."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30" }],
    coordinates: [
      [-74.0178, 40.7043],
      [-74.0159, 40.7048],
      [-74.0139, 40.7052],
    ],
  },
  {
    id: "bayard-street",
    corridor: "Lower Manhattan Colonial Streets",
    currentName: "Bayard Street",
    segmentLabel: "Chinatown / Civic edge",
    bounds: "Historic estate area from Canal to Bleecker, Broadway to Bowery",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Nicholas Bayard, nephew of Peter Stuyvesant and mayor in 1686; the street marked a boundary of Bayard estate lands.",
    timeline: ["1686: Nicholas Bayard serves as mayor."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30" }],
    coordinates: [
      [-73.9994, 40.7144],
      [-73.9965, 40.715],
      [-73.9939, 40.7156],
    ],
  },
  {
    id: "baxter-street",
    corridor: "Chinatown Historic Streets",
    currentName: "Baxter Street",
    segmentLabel: "North-south Chinatown segment",
    bounds: "Lower Manhattan / Chinatown",
    altNames: [],
    formerNames: ["Orange Street"],
    origin:
      "Renamed for Charles Baxter, a legislator killed in the 1848 Battle of Chapultepec; formerly Orange Street.",
    timeline: ["1848: Baxter dies in the war with Mexico.", "19th century: Orange Street renamed Baxter Street."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30" }],
    coordinates: [
      [-73.9998, 40.7132],
      [-73.9988, 40.7178],
      [-73.9979, 40.7225],
    ],
  },
  {
    id: "beach-street",
    corridor: "Tribeca Historic Streets",
    currentName: "Beach Street",
    segmentLabel: "South of Canal Street",
    bounds: "Just south of Canal Street",
    altNames: [],
    formerNames: [],
    origin:
      "A corruption of 'Bache', originally tied to Paul Bache and the Lispenard Meadows holdings in the late 18th century.",
    timeline: ["Late 18th century: Early Lispenard-area street layout."],
    confidence: "medium",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30" }],
    coordinates: [
      [-74.0092, 40.7191],
      [-74.0069, 40.7193],
      [-74.0044, 40.7196],
    ],
  },
  {
    id: "east-broadway",
    corridor: "Lower East Side Arterials",
    currentName: "East Broadway",
    segmentLabel: "Northward from Chatham Square",
    bounds: "Lower East Side / Two Bridges corridor",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Broadway as a planned relief corridor for downtown traffic; the route existed as a lane before 1732 and was officially named around 1830.",
    timeline: ["Before 1732: Lane-era alignment.", "Circa 1830: Official East Broadway naming."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow)" }],
    coordinates: [
      [-73.9989, 40.7149],
      [-73.9942, 40.7178],
      [-73.9891, 40.7211],
    ],
  },
  {
    id: "east-end-avenue",
    corridor: "Upper East Side River Edge",
    currentName: "East End Avenue",
    segmentLabel: "79th St to 90th St stretch",
    bounds: "79th Street to 90th Street",
    altNames: [],
    formerNames: [],
    origin:
      "Named for its location as the eastern terminal avenue in that Upper East Side section.",
    timeline: [],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow)" }],
    coordinates: [
      [-73.9488, 40.7735],
      [-73.9476, 40.7794],
      [-73.9464, 40.7854],
    ],
  },
  {
    id: "east-houston-street",
    corridor: "Historic Waterway Streets",
    currentName: "East Houston Street",
    segmentLabel: "Bowery eastbound segment",
    bounds: "East of the Bowery in the old northern-boundary corridor",
    altNames: [],
    formerNames: ["North Street"],
    origin:
      "Formerly known as North Street when it marked part of the city's northern edge in the early 19th century; later absorbed into the Houston Street naming convention.",
    timeline: ["Early 19th century: North Street usage.", "Later: East Houston designation standardized."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow)" }],
    coordinates: [
      [-73.9922, 40.7288],
      [-73.9858, 40.7289],
      [-73.9791, 40.729],
      [-73.9721, 40.729],
    ],
  },
  {
    id: "edgar-street",
    corridor: "Lower Manhattan Short Streets",
    currentName: "Edgar Street",
    segmentLabel: "Near Greenwich Street",
    bounds: "Battery Park City fringe / Greenwich Street edge",
    altNames: [],
    formerNames: ["Tuyn Paat", "Garden Lane", "Tin Pot Alley"],
    origin:
      "Named for the Edgar family mansion approach road; in Dutch and early British eras it carried names meaning Garden Lane before settling on Edgar Street.",
    timeline: ["1830s: Edgar shipping prominence era.", "1953: Street alignment shifted northward."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow)" }],
    coordinates: [
      [-74.0164, 40.7091],
      [-74.0158, 40.7093],
      [-74.0152, 40.7095],
    ],
  },
  {
    id: "edgecombe-avenue",
    corridor: "Harlem Heights Avenues",
    currentName: "Edgecombe Avenue",
    segmentLabel: "Hill-crest upper Manhattan avenue",
    bounds: "Upper Manhattan ridge corridor",
    altNames: [],
    formerNames: [],
    origin:
      "Named for its topographic setting on the crest of a hill, using the Saxon root 'combe'; reportedly proposed by the West Side Association in 1872.",
    timeline: ["1872: Name proposal context."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow)" }],
    coordinates: [
      [-73.9448, 40.8205],
      [-73.9427, 40.8288],
      [-73.9409, 40.8367],
      [-73.9394, 40.8444],
    ],
  },
  {
    id: "edwin-m-morgan-place",
    corridor: "Civic / Postal Commemorations",
    currentName: "Edwin M. Morgan Place",
    segmentLabel: "Small commemorative place",
    bounds: "Lower Manhattan civic area",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Edwin M. Morgan, New York postmaster from 1897 until his death in 1925, recognized for long postal service and administrative leadership.",
    timeline: ["1897-1925: Morgan postmaster period."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow)" }],
    coordinates: [
      [-74.0062, 40.7139],
      [-74.0052, 40.7142],
      [-74.0041, 40.7144],
    ],
  },
  {
    id: "eldridge-street",
    corridor: "Lower East Side Historic Avenues",
    currentName: "Eldridge Street",
    segmentLabel: "LES north-south segment",
    bounds: "Lower East Side",
    altNames: [],
    formerNames: ["Third Street"],
    origin:
      "Originally Third Street on de Lancey farm land, it was later renamed for Lt. Joseph C. Eldridge after his War of 1812 death in 1813.",
    timeline: ["Pre-1767: Third Street-era layout.", "1813: Renamed in Eldridge's honor."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow)" }],
    coordinates: [
      [-73.9928, 40.7151],
      [-73.992, 40.7212],
      [-73.9912, 40.7273],
    ],
  },
  {
    id: "elizabeth-street",
    corridor: "SoHo / NoLIta Historic Streets",
    currentName: "Elizabeth Street",
    segmentLabel: "South-to-north local corridor",
    bounds: "Extended to Bleecker Street",
    altNames: [],
    formerNames: [],
    origin:
      "Likely named for a female relative of a local landowner; laid out before 1755 and extended northward to Bleecker Street in 1816.",
    timeline: ["Pre-1755: Early street layout.", "1816: Extension to Bleecker Street."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow)" }],
    coordinates: [
      [-73.9978, 40.7163],
      [-73.9969, 40.7225],
      [-73.9961, 40.7287],
      [-73.9951, 40.7346],
    ],
  },
  {
    id: "elk-street",
    corridor: "Civic Center Streets",
    currentName: "Elk Street",
    segmentLabel: "Civic Center short street",
    bounds: "Lower Manhattan civic district",
    altNames: [],
    formerNames: ["Elm Street"],
    origin:
      "Renamed from Elm Street in 1939 for the Benevolent and Protective Order of Elks, whose roots trace to the 1867 Jolly Corks theatrical club.",
    timeline: ["1867: Jolly Corks / Elks origin context.", "1939: Elm Street renamed Elk Street."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow)" }],
    coordinates: [
      [-73.9997, 40.7132],
      [-73.9988, 40.7147],
      [-73.9979, 40.7162],
    ],
  },
  {
    id: "ellwood-street",
    corridor: "Northern Manhattan Upland Streets",
    currentName: "Ellwood Street",
    segmentLabel: "Dyckman lands traverse",
    bounds: "Northern Manhattan / old Dyckman lands",
    altNames: [],
    formerNames: [],
    origin:
      "The namesake remains uncertain; the street was laid out in 1891 and named in 1911, with Revolutionary-era military shelter remains reportedly found during grading.",
    timeline: ["1891: Street laid out.", "1911: Naming formalized."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow)" }],
    coordinates: [
      [-73.9266, 40.8721],
      [-73.9249, 40.8742],
      [-73.9232, 40.8764],
    ],
  },
  {
    id: "ericsson-place",
    corridor: "Tribeca Historic Streets",
    currentName: "Ericsson Place",
    segmentLabel: "Beach Street spur",
    bounds: "Part of Beach Street corridor",
    altNames: [],
    formerNames: [],
    origin:
      "Named for John Ericsson, designer of the ironclad Monitor; he lived on Beach Street from 1864 to 1889 and the place is effectively part of that street network.",
    timeline: ["1864-1889: Ericsson residence period."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow)" }],
    coordinates: [
      [-74.0082, 40.7194],
      [-74.0077, 40.7197],
      [-74.0071, 40.72],
    ],
  },
  {
    id: "essex-street",
    corridor: "Lower East Side Historic Avenues",
    currentName: "Essex Street",
    segmentLabel: "LES north-south corridor",
    bounds: "Lower East Side",
    altNames: [],
    formerNames: [],
    origin:
      "Named for the English county of Essex.",
    timeline: [],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow)" }],
    coordinates: [
      [-73.9889, 40.7146],
      [-73.988, 40.7208],
      [-73.9872, 40.7271],
      [-73.9864, 40.7331],
    ],
  },
  {
    id: "exchange-place-alley",
    corridor: "Financial District Colonial Streets",
    currentName: "Exchange Place and Exchange Alley",
    segmentLabel: "FiDi short connectors",
    bounds: "Lower Manhattan exchange district",
    altNames: [],
    formerNames: ["Tuyn Street", "Tuijn Street", "Garden Street"],
    origin:
      "Named for the merchants' exchange institution formalized in 1670; earlier names reflected its garden/pasture character in Dutch and English usage.",
    timeline: ["1670: Merchants Exchange formally established."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow)" }],
    coordinates: [
      [-74.0104, 40.7055],
      [-74.0089, 40.7057],
      [-74.0074, 40.7059],
    ],
  },
  {
    id: "exterior-street",
    corridor: "Harlem River Shore Streets",
    currentName: "Exterior Street",
    segmentLabel: "Harlem River industrial edge",
    bounds: "Harlem River shore",
    altNames: [],
    formerNames: [],
    origin:
      "Named for its position along Manhattan's Harlem River edge and created to accommodate industry during Harlem River Drive-era infrastructure development.",
    timeline: [],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow)" }],
    coordinates: [
      [-73.9303, 40.8125],
      [-73.9289, 40.8194],
      [-73.9275, 40.8263],
    ],
  },
  {
    id: "extra-place",
    corridor: "East Village Short Streets",
    currentName: "Extra Place",
    segmentLabel: "Off East 1st near 2nd Ave",
    bounds: "Off East First, near Second Avenue",
    altNames: [],
    formerNames: [],
    origin:
      "Named for the 'extra' strip left after Philip Minthorne's 110-acre farm was divided among nine heirs following his death in 1802.",
    timeline: ["1802: Minthorne estate partition context."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow)" }],
    coordinates: [
      [-73.989, 40.7236],
      [-73.9886, 40.724],
    ],
  },
  {
    id: "beak-street",
    corridor: "Tribeca / Canal Fringe",
    currentName: "Beak Street",
    segmentLabel: "Tiny Tribeca side street",
    bounds: "Small side street near lower Canal area",
    altNames: [],
    formerNames: [],
    origin:
      "Likely named for a local person or family; formal naming was approved by the Board of Aldermen on May 11, 1925.",
    timeline: ["1925: Official naming action by Board of Aldermen."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30 (batch cite: 2167-2168)" }],
    coordinates: [
      [-74.0101, 40.721],
      [-74.0096, 40.7213],
      [-74.009, 40.7216],
    ],
  },
  {
    id: "beaver-street",
    corridor: "Financial District Colonial Streets",
    currentName: "Beaver Street",
    segmentLabel: "Broadway to Broad Street segment",
    bounds: "Between Broadway and Broad Street",
    altNames: [],
    formerNames: [],
    origin:
      "Named for the beaver-centered fur trade economy of early New York, when pelts functioned as a major store of value.",
    timeline: ["17th century: Fur trade prominence in colonial New York."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30 (batch cite: 2170-2171)" }],
    coordinates: [
      [-74.011, 40.7058],
      [-74.0088, 40.7061],
      [-74.0064, 40.7063],
    ],
  },
  {
    id: "bedford-street",
    corridor: "Greenwich Village Historic Streets",
    currentName: "Bedford Street",
    segmentLabel: "Village north-south section",
    bounds: "Greenwich Village",
    altNames: [],
    formerNames: [],
    origin:
      "Mapped before 1799 and believed to be named after Bedford Street in London, though the exact naming rationale is not recorded.",
    timeline: ["Pre-1799: Street appears on maps."],
    confidence: "medium",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30 (batch cite: 2185-2186)" }],
    coordinates: [
      [-74.0054, 40.7314],
      [-74.0047, 40.7354],
      [-74.004, 40.7392],
    ],
  },
  {
    id: "beekman-place",
    corridor: "East Midtown Historic Enclaves",
    currentName: "Beekman Place",
    segmentLabel: "East River enclave near 51st St",
    bounds: "Near East River at 51st Street",
    altNames: [],
    formerNames: [],
    origin:
      "Named for the Beekman family; James Beekman built the nearby Mount Pleasant mansion in 1766. The district was substantially rehabilitated in the 1920s.",
    timeline: ["1766: Mount Pleasant built.", "1920s: Area rehabilitation wave."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30 (batch cite: 2174-2181)" }],
    coordinates: [
      [-73.963, 40.7566],
      [-73.9618, 40.7585],
      [-73.9608, 40.7603],
    ],
  },
  {
    id: "beekman-street",
    corridor: "Lower Manhattan Colonial Streets",
    currentName: "Beekman Street",
    segmentLabel: "Civic Center to East River",
    bounds: "Nassau Street to East River",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Willem Beeckman, who arrived in 1647 and later served multiple mayoral terms; the street crosses former Beeckman landholdings.",
    timeline: ["1647: Beeckman arrives in New Amsterdam.", "1670: Beeckman farm holdings established."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30 (batch cite: 2188-2192)" }],
    coordinates: [
      [-74.0079, 40.7108],
      [-74.0048, 40.7109],
      [-74.0015, 40.711],
      [-73.9983, 40.711],
    ],
  },
  {
    id: "bennett-avenue",
    corridor: "Washington Heights Avenues",
    currentName: "Bennett Avenue",
    segmentLabel: "Northern Manhattan ridge section",
    bounds: "Washington Heights / Inwood transition",
    altNames: [],
    formerNames: [],
    origin:
      "Named for New York Herald founder James Gordon Bennett Sr., who maintained a country place in the area.",
    timeline: ["1835: New York Herald founded.", "1872: Bennett dies."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30 (batch cite: 2212-2214)" }],
    coordinates: [
      [-73.9346, 40.8542],
      [-73.9332, 40.8604],
      [-73.9318, 40.8666],
    ],
  },
  {
    id: "benson-street",
    corridor: "Lower Manhattan Legacy Streets",
    currentName: "Benson Street",
    segmentLabel: "Historic legal district reference",
    bounds: "Lower Manhattan (historic reference)",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Egbert Benson, New York's first attorney general (appointed 1777), Continental Congress delegate, judge, and New-York Historical Society founder.",
    timeline: ["1777: Benson appointed New York attorney general."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30 (batch cite: 2217-2220)" }],
    coordinates: [
      [-74.0105, 40.7132],
      [-74.0094, 40.7135],
      [-74.0083, 40.7137],
    ],
  },
  {
    id: "bethune-street",
    corridor: "West Village Philanthropy Streets",
    currentName: "Bethune Street",
    segmentLabel: "West Village crosstown segment",
    bounds: "West Village",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Johanna Graham Bethune, educator and philanthropist who ceded land for the street and helped found major charitable institutions including the New York Orphan Asylum.",
    timeline: ["1806: New York Orphan Asylum co-founded.", "Early 19th century: Land cession and naming context."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30 (batch cite: 2233-2235)" }],
    coordinates: [
      [-74.0098, 40.7406],
      [-74.0079, 40.7411],
      [-74.0061, 40.7416],
    ],
  },
  {
    id: "bleecker-street",
    corridor: "Greenwich Village Core Streets",
    currentName: "Bleecker Street",
    segmentLabel: "Village east-west corridor",
    bounds: "Greenwich Village and NoHo stretches",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Anthony Bleecker; the road already crossed Bleecker family farm lands before nearby parcels were deeded to the city in 1807.",
    timeline: ["1807: Related Bleecker lands deeded to city."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30 (batch cite: 2247-2248)" }],
    coordinates: [
      [-74.0108, 40.7313],
      [-74.0036, 40.7287],
      [-73.9971, 40.7263],
      [-73.9918, 40.7245],
    ],
  },
  {
    id: "bloomfield-street",
    corridor: "West Village Historic Streets",
    currentName: "Bloomfield Street",
    segmentLabel: "Short West Village segment",
    bounds: "West Village waterfront-adjacent area",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Brigadier General Joseph Bloomfield, Revolutionary veteran and later commander of New York harbor defenses during the War of 1812.",
    timeline: ["War of 1812: Harbor defense leadership era."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30 (batch cite: 2238)" }],
    coordinates: [
      [-74.0088, 40.7396],
      [-74.0076, 40.7401],
      [-74.0064, 40.7406],
    ],
  },
  {
    id: "bogardus-place",
    corridor: "Fort Tryon Area Streets",
    currentName: "Bogardus Place",
    segmentLabel: "Fort Tryon vicinity",
    bounds: "Near Fort Tryon Park",
    altNames: [],
    formerNames: [],
    origin:
      "Named for the Bogardus family, whose estate holdings covered portions of the present Fort Tryon area; formal naming dates to 1912.",
    timeline: ["1912: Street formally named."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30 (batch cite: 2241-2244)" }],
    coordinates: [
      [-73.9338, 40.8618],
      [-73.9327, 40.8635],
      [-73.9315, 40.8652],
    ],
  },
  {
    id: "bond-street",
    corridor: "NoHo Historic Streets",
    currentName: "Bond Street",
    segmentLabel: "NoHo / Broadway-adjacent section",
    bounds: "Near Broadway",
    altNames: [],
    formerNames: [],
    origin:
      "The specific namesake remains uncertain; period accounts note the name was suggested by Samuel Jones (associated with Great Jones Street).",
    timeline: ["Early 1800s: Naming period."],
    confidence: "medium",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30 (batch cite: 2258-2259)" }],
    coordinates: [
      [-73.9948, 40.7264],
      [-73.9926, 40.7268],
      [-73.9903, 40.7272],
    ],
  },
  {
    id: "bowling-green",
    corridor: "Colonial-Era Spaces",
    currentName: "Bowling Green",
    segmentLabel: "Historic plaza at Manhattan's tip",
    bounds: "Near Battery Park",
    altNames: [],
    formerNames: [],
    origin:
      "Named for a fenced bowling field leased in 1732 to leading colonial figures; rent was the famous token payment of one peppercorn per year.",
    timeline: ["1732: Leased for private bowling green use."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30 (batch cite: 2267-2268)" }],
    coordinates: [
      [-74.0138, 40.7046],
      [-74.0128, 40.7049],
      [-74.0118, 40.7052],
      [-74.0127, 40.7056],
      [-74.0138, 40.7046],
    ],
  },
  {
    id: "bradhurst-avenue",
    corridor: "Hamilton Heights Avenues",
    currentName: "Bradhurst Avenue",
    segmentLabel: "Hamilton Heights segment",
    bounds: "Near The Grange",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Dr. Samuel Bradhurst, an 18th-century physician who owned nearby country property adjacent to Hamilton's The Grange area.",
    timeline: ["Late 18th century: Bradhurst estate period in upper Manhattan."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30 (batch cite: 2263-2265)" }],
    coordinates: [
      [-73.9596, 40.8183],
      [-73.9583, 40.8241],
      [-73.9571, 40.8299],
    ],
  },
  {
    id: "bridge-street",
    corridor: "Financial District Colonial Streets",
    currentName: "Bridge Street",
    segmentLabel: "Old Broad Canal crossing line",
    bounds: "Historic crossing of Broad Street",
    altNames: [],
    formerNames: [],
    origin:
      "Named for a bridge that once crossed Broad Street when Broad was still a tidal canal (the Broad Canal).",
    timeline: ["17th century: Canal-crossing bridge era."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30 (batch cite: 2276)" }],
    coordinates: [
      [-74.0108, 40.7069],
      [-74.0092, 40.7072],
      [-74.0077, 40.7075],
    ],
  },
  {
    id: "broad-street",
    corridor: "Financial District Colonial Streets",
    currentName: "Broad Street",
    segmentLabel: "Lower Manhattan financial canyon",
    bounds: "Lower Manhattan",
    altNames: [],
    formerNames: ["Broad Canal (waterway predecessor)"],
    origin:
      "Named for the Broad Canal that once occupied the corridor before being filled in 1676.",
    timeline: ["1676: Broad Canal filled, paving the way for street alignment."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 30 (batch cite: 2289-2290)" }],
    coordinates: [
      [-74.0112, 40.7044],
      [-74.0104, 40.7085],
      [-74.0095, 40.7128],
    ],
  },
  {
    id: "charles-street",
    corridor: "Greenwich Village Historic Streets",
    currentName: "Charles Street",
    segmentLabel: "West Village crosstown segment",
    bounds: "Greenwich Village",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Charles Christopher Amos, whose family held part of former Admiral Sir Peter Warren estate lands in Greenwich Village; nearby streets were also named Christopher and Amos (later West 10th Street).",
    timeline: ["18th century: Amos-associated village land development period."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 4" }],
    coordinates: [
      [-74.0084, 40.7361],
      [-74.0058, 40.7368],
      [-74.0031, 40.7376],
    ],
  },
  {
    id: "charles-h-revson-plaza",
    corridor: "Morningside Heights Plazas",
    currentName: "Charles H. Revson Plaza",
    segmentLabel: "Columbia University plaza",
    bounds: "Columbia University area",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Charles Haskell Revson, founder of Revlon, in recognition of his philanthropic benefactions tied to Columbia University.",
    timeline: ["20th century: Revson philanthropic naming period."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 4" }],
    coordinates: [
      [-73.9598, 40.8083],
      [-73.9589, 40.8088],
      [-73.958, 40.8092],
    ],
  },
  {
    id: "charlton-street",
    corridor: "SoHo / Hudson Square Historic Streets",
    currentName: "Charlton Street",
    segmentLabel: "Hudson Square crosstown segment",
    bounds: "Lower Manhattan west side",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Dr. John Charlton, an English surgeon who remained in New York after the Revolutionary War and later led the New York Medical Society; street naming dates to 1807.",
    timeline: ["1807: Street naming associated with Dr. John Charlton."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 4" }],
    coordinates: [
      [-74.0094, 40.7271],
      [-74.0068, 40.7277],
      [-74.0043, 40.7283],
    ],
  },
  {
    id: "chatham-square",
    corridor: "Chinatown Gateways",
    currentName: "Chatham Square",
    segmentLabel: "Bowery/Park Row convergence",
    bounds: "Lower Manhattan",
    altNames: ["Kim Lau Square"],
    formerNames: [],
    origin:
      "Named for William Pitt, Earl of Chatham. In the post-World War II era, the area also acquired the Chinese-American commemorative alias Kim Lau Square.",
    timeline: ["Pre-Revolution: Chatham naming reference.", "Post-WWII: Kim Lau Square co-association."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 4" }],
    coordinates: [
      [-73.9982, 40.7136],
      [-73.9967, 40.7142],
      [-73.9954, 40.7147],
      [-73.9942, 40.7152],
    ],
  },
  {
    id: "chelsea-square",
    corridor: "Chelsea Historic Places",
    currentName: "Chelsea Square",
    segmentLabel: "Historic Chelsea naming area",
    bounds: "22nd Street west of Ninth Avenue (historic reference)",
    altNames: [],
    formerNames: [],
    origin:
      "The Chelsea name references London's Royal Chelsea Hospital and was adopted for Captain Thomas Clarke's farm in this area, later shaping neighborhood place naming.",
    timeline: ["Late 18th century: Chelsea farm naming context."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 4" }],
    coordinates: [
      [-74.0063, 40.7472],
      [-74.0049, 40.7477],
      [-74.0035, 40.7481],
    ],
  },
  {
    id: "cherokee-place",
    corridor: "Upper East Side Political History Streets",
    currentName: "Cherokee Place",
    segmentLabel: "Short UES block",
    bounds: "Near 79th Street between First and Second Avenues",
    altNames: [],
    formerNames: [],
    origin:
      "Named in 1913 for the Cherokee Club, a politically connected Tammany Hall organization whose headquarters stood nearby.",
    timeline: ["1913: Street officially named."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 4" }],
    coordinates: [
      [-73.9519, 40.7738],
      [-73.9508, 40.7742],
      [-73.9497, 40.7746],
    ],
  },
  {
    id: "cherry-street",
    corridor: "Lower East Side Colonial Streets",
    currentName: "Cherry Street",
    segmentLabel: "East River edge corridor",
    bounds: "Lower Manhattan",
    altNames: [],
    formerNames: [],
    origin:
      "Named for a notable 17th-century cherry orchard associated with Goovert Loockermans; in 1789, George Washington's residence on Cherry Street served as an early presidential home.",
    timeline: ["1660s: Loockermans cherry orchard.", "1789: Washington residence era."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 4" }],
    coordinates: [
      [-73.9956, 40.7111],
      [-73.9914, 40.7117],
      [-73.9871, 40.7123],
      [-73.9832, 40.7128],
    ],
  },
  {
    id: "chisum-place",
    corridor: "Harlem River Edge Streets",
    currentName: "Chisum Place",
    segmentLabel: "Tiny Harlem Houses frontage street",
    bounds: "Near W 141st St and Harlem River Drive",
    altNames: [],
    formerNames: [],
    origin:
      "A very short street formally named on April 4, 1961; surviving records in source material do not clearly identify the honoree.",
    timeline: ["1961: Official naming date."],
    confidence: "medium",
    sources: [{ label: "The Street Book (Henry Moscow), batch 4" }],
    coordinates: [
      [-73.9366, 40.8195],
      [-73.9357, 40.82],
      [-73.9348, 40.8204],
    ],
  },
  {
    id: "chittenden-avenue",
    corridor: "Fort Tryon / Washington Heights Streets",
    currentName: "Chittenden Avenue",
    segmentLabel: "Northern Manhattan avenue segment",
    bounds: "Historic Chittenden holdings from 185th to 198th Streets",
    altNames: [],
    formerNames: [],
    origin:
      "Named for landowner Lucius Chittenden; period descriptions place his home near what is now Fort Tryon Park. Avenue naming is associated with 1911.",
    timeline: ["1911: Avenue naming date."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 4" }],
    coordinates: [
      [-73.9357, 40.8525],
      [-73.9342, 40.8576],
      [-73.9328, 40.8623],
      [-73.9313, 40.8668],
    ],
  },
  {
    id: "christopher-street",
    corridor: "Greenwich Village Historic Streets",
    currentName: "Christopher Street",
    segmentLabel: "West Village crosstown corridor",
    bounds: "Greenwich Village",
    altNames: [],
    formerNames: ["Skinner Road"],
    origin:
      "Named for Charles Christopher Amos. Earlier naming traditions reference Skinner Road, tied to Colonel William Skinner, connected by marriage to Admiral Sir Peter Warren's family.",
    timeline: ["18th century: Street naming in village estate subdivision period."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 4" }],
    coordinates: [
      [-74.0113, 40.7332],
      [-74.0078, 40.734],
      [-74.0043, 40.7348],
      [-74.0009, 40.7355],
    ],
  },
  {
    id: "chrystie-street",
    corridor: "Lower East Side Military Memorial Streets",
    currentName: "Chrystie Street",
    segmentLabel: "LES north-south segment",
    bounds: "Lower East Side / Chinatown edge",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Lt. Col. John Chrystie, a Columbia graduate and War of 1812 officer who was wounded and captured at Queenstown Heights and later died.",
    timeline: ["1812-1813: War service and death of John Chrystie."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 4" }],
    coordinates: [
      [-73.9938, 40.7158],
      [-73.9928, 40.7213],
      [-73.9919, 40.7267],
      [-73.991, 40.7318],
    ],
  },
  {
    id: "church-street",
    corridor: "Trinity Church Legacy Streets",
    currentName: "Church Street",
    segmentLabel: "Downtown to Tribeca spine",
    bounds: "Lower Manhattan",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Trinity Church. The route existed by 1761, expanded in 1784, and included portions later ceded to the city by church ownership.",
    timeline: ["1761: Early documented street existence.", "1784: Extension phase.", "1804: Trinity cession of owned segment."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 4" }],
    coordinates: [
      [-74.0103, 40.7081],
      [-74.0096, 40.7147],
      [-74.0088, 40.7214],
      [-74.008, 40.7282],
    ],
  },
  {
    id: "city-hall-park-square",
    corridor: "Civic Core Historic Grounds",
    currentName: "City Hall Park and Square",
    segmentLabel: "Civic center open space",
    bounds: "Near City Hall",
    altNames: [],
    formerNames: ["De Vlackte (the Flat)", "The Commons"],
    origin:
      "Named for City Hall and built over older communal grounds known first as De Vlackte in Dutch-era usage and later as the Commons.",
    timeline: ["17th century: Dutch-era common land.", "1803: City Hall era consolidation."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 4" }],
    coordinates: [
      [-74.0089, 40.712],
      [-74.0068, 40.7124],
      [-74.0055, 40.7134],
      [-74.0063, 40.7148],
      [-74.0082, 40.7145],
      [-74.0091, 40.7131],
      [-74.0089, 40.712],
    ],
  },
  {
    id: "claremont-avenue",
    corridor: "Morningside / Riverside Historic Avenues",
    currentName: "Claremont Avenue",
    segmentLabel: "Uptown west-side avenue section",
    bounds: "Riverside Park area",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Claremont Mansion in the area now associated with Riverside and Morningside heights landscapes; Michael Hogan's early-1800s ownership linked the name to County Clare/Claremont traditions.",
    timeline: ["Late 18th to early 19th century: Mansion era.", "1804: Hogan acquisition and naming context."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 4" }],
    coordinates: [
      [-73.9644, 40.8089],
      [-73.9638, 40.8132],
      [-73.9632, 40.8174],
      [-73.9626, 40.8216],
    ],
  },
  {
    id: "clarkson-street",
    corridor: "West Village Historic Streets",
    currentName: "Clarkson Street",
    segmentLabel: "Village crosstown segment",
    bounds: "West Village",
    altNames: [],
    formerNames: ["Morton Street"],
    origin:
      "Named in 1807 by the Common Council for Matthew Clarkson, a Revolutionary-era figure and later civic leader; source traditions also note a former Morton naming reference.",
    timeline: ["1807: Common Council naming action."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 4" }],
    coordinates: [
      [-74.0091, 40.7312],
      [-74.0065, 40.7318],
      [-74.0038, 40.7325],
    ],
  },
  {
    id: "cleveland-place",
    corridor: "Nolita Historic Streets",
    currentName: "Cleveland Place",
    segmentLabel: "Short Nolita connector",
    bounds: "Historic association text references Midtown blocks; modern street is in Nolita",
    altNames: [],
    formerNames: [],
    origin:
      "Associated with President Grover Cleveland in source tradition. Historical notes in the source include references to his early New York employment before presidency.",
    timeline: ["1853-1854: Cleveland in New York before national office."],
    confidence: "medium",
    sources: [{ label: "The Street Book (Henry Moscow), batch 4" }],
    coordinates: [
      [-73.9979, 40.7213],
      [-73.9968, 40.7218],
      [-73.9957, 40.7222],
    ],
  },
  {
    id: "cliff-street",
    corridor: "Financial District Colonial Streets",
    currentName: "Cliff Street",
    segmentLabel: "Historic FiDi side street",
    bounds: "Lower Manhattan",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Dirck van der Clyff, whose property was cut for the street in the early 18th century; opening as a public street came in 1786.",
    timeline: ["Early 18th century: Landholder naming context.", "1786: Street opened."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 4" }],
    coordinates: [
      [-74.0081, 40.7085],
      [-74.0069, 40.7088],
      [-74.0057, 40.7091],
    ],
  },
  {
    id: "clinton-street",
    corridor: "Lower East Side Historic Avenues",
    currentName: "Clinton Street",
    segmentLabel: "LES north-south corridor",
    bounds: "Lower East Side",
    altNames: [],
    formerNames: ["Warren Street"],
    origin:
      "Named in 1792 for George Clinton, Revolutionary general and first governor of New York under the post-Independence constitution; formerly known as Warren Street.",
    timeline: ["1792: Clinton naming date."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 4" }],
    coordinates: [
      [-73.9852, 40.7148],
      [-73.9842, 40.7207],
      [-73.9833, 40.7266],
      [-73.9824, 40.7325],
    ],
  },
  {
    id: "delancey-street",
    corridor: "Lower East Side Historic Arterials",
    currentName: "Delancey Street",
    segmentLabel: "Bowery to East River",
    bounds: "Bowery to East River; historic estate edge context",
    altNames: [],
    formerNames: [],
    origin:
      "Named for James de Lancey, an influential colonial jurist and lieutenant governor; the street marked the northern edge of major de Lancey holdings.",
    timeline: ["1731-1760: De Lancey judicial and political prominence.", "18th century: Estate boundary significance."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 5" }],
    coordinates: [
      [-73.9969, 40.7188],
      [-73.9916, 40.7191],
      [-73.9861, 40.7194],
      [-73.9809, 40.7198],
      [-73.9755, 40.7202],
    ],
  },
  {
    id: "depew-place",
    corridor: "Midtown Legacy Streets",
    currentName: "Depew Place",
    segmentLabel: "Grand Central vicinity historic passage",
    bounds: "Midtown East / Grand Central area",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Chauncey M. Depew, railroad executive, senator, and public figure associated with the New York Central era.",
    timeline: ["Late 19th century: Railroad prominence.", "1900-1912: U.S. Senate service."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 5" }],
    coordinates: [
      [-73.9786, 40.7519],
      [-73.9775, 40.7523],
      [-73.9765, 40.7528],
    ],
  },
  {
    id: "depeyster-street",
    corridor: "Lower Manhattan Colonial Streets",
    currentName: "Depeyster Street",
    segmentLabel: "Colonial civic corridor",
    bounds: "Lower Manhattan historic alignment",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Abraham de Peyster, late 17th-century mayor and chief justice; linked to the de Peyster family estate and civic benefactions.",
    timeline: ["1691-1695: Abraham de Peyster mayoralty period."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 5" }],
    coordinates: [
      [-74.0109, 40.7055],
      [-74.0096, 40.7059],
      [-74.0084, 40.7063],
    ],
  },
  {
    id: "desbrosses-street",
    corridor: "Tribeca Colonial Commerce Streets",
    currentName: "Desbrosses Street",
    segmentLabel: "Tribeca east-west segment",
    bounds: "Tribeca",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Elias Desbrosses, pre-Revolutionary alderman and merchant tied to early New York commerce and the Chamber of Commerce.",
    timeline: ["18th century: Desbrosses civic and mercantile era."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 5" }],
    coordinates: [
      [-74.0115, 40.7224],
      [-74.0091, 40.7226],
      [-74.0067, 40.7229],
    ],
  },
  {
    id: "dey-street",
    corridor: "Lower Manhattan Historic Streets",
    currentName: "Dey Street",
    segmentLabel: "WTC / Fulton area crosstown",
    bounds: "Broadway toward Hudson-side historic reach",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Dirck Theunis Dey, associated with a large leased farm (from 1677); the road gained strategic use as ferry patterns expanded in the 18th century.",
    timeline: ["1677: Dey lease period.", "1763: Ferry-related corridor use expands."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 5" }],
    coordinates: [
      [-74.0113, 40.7107],
      [-74.0085, 40.7109],
      [-74.0058, 40.7111],
    ],
  },
  {
    id: "division-street",
    corridor: "Lower East Side Boundary Streets",
    currentName: "Division Street",
    segmentLabel: "Historic farm-boundary corridor",
    bounds: "Between former de Lancey and Rutgers lands",
    altNames: [],
    formerNames: [],
    origin:
      "Named for its role as a dividing line between major colonial farms; historical accounts describe a rope-walk no-man's-land along the corridor.",
    timeline: ["18th century: Farm-boundary and rope-walk use."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 5" }],
    coordinates: [
      [-73.9986, 40.7146],
      [-73.9941, 40.7152],
      [-73.9893, 40.7159],
      [-73.9844, 40.7167],
    ],
  },
  {
    id: "dominick-street",
    corridor: "SoHo / Hudson Square Historic Streets",
    currentName: "Dominick Street",
    segmentLabel: "Hudson Square segment",
    bounds: "West SoHo / Hudson Square",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Georges Dominick, an 18th-century refugee from France who became active in Trinity Church governance and militia leadership.",
    timeline: ["Mid-18th century: Dominick civic role period."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 5" }],
    coordinates: [
      [-74.0089, 40.7278],
      [-74.0065, 40.7281],
      [-74.0042, 40.7284],
    ],
  },
  {
    id: "dongan-place",
    corridor: "Harlem Colonial Governance Streets",
    currentName: "Dongan Place",
    segmentLabel: "Upper Manhattan short avenue",
    bounds: "Harlem / Washington Heights vicinity",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Governor Thomas Dongan (1683-1688), associated with New York's Charter of Liberties and Privileges and early constitutional governance.",
    timeline: ["1683-1688: Dongan governorship."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 5" }],
    coordinates: [
      [-73.9432, 40.8402],
      [-73.9422, 40.8431],
      [-73.9412, 40.846],
    ],
  },
  {
    id: "donnellon-square",
    corridor: "Uptown Memorial Squares",
    currentName: "Donnellon Square",
    segmentLabel: "WWI memorial square",
    bounds: "Upper Manhattan",
    altNames: [],
    formerNames: [],
    origin:
      "Named in 1921 by the Board of Aldermen for a local resident killed in World War I.",
    timeline: ["1921: Square naming action."],
    confidence: "medium",
    sources: [{ label: "The Street Book (Henry Moscow), batch 5" }],
    coordinates: [
      [-73.9309, 40.8686],
      [-73.9299, 40.8693],
      [-73.9289, 40.8701],
      [-73.9309, 40.8686],
    ],
  },
  {
    id: "dover-street",
    corridor: "Seaport Colonial Streets",
    currentName: "Dover Street",
    segmentLabel: "Pearl Street / East River edge",
    bounds: "At Pearl Street / East River",
    altNames: [],
    formerNames: [],
    origin:
      "Named after the English port city; area associations include very early ferry operations linked to Brooklyn crossings.",
    timeline: ["1638: Early ferry context.", "Colonial era: Port-comparison naming usage."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 5" }],
    coordinates: [
      [-74.0018, 40.7087],
      [-74.0008, 40.7094],
      [-73.9997, 40.7101],
    ],
  },
  {
    id: "downing-street",
    corridor: "West Village Historic Streets",
    currentName: "Downing Street",
    segmentLabel: "Village short connector",
    bounds: "Greenwich Village",
    altNames: [],
    formerNames: [],
    origin:
      "Namesake remains uncertain; possible references include Downing's oyster-house legacy or Sir George Downing. The street layout predates 1799.",
    timeline: ["Pre-1799: Street laid out.", "1830s: Downing's oyster-house era context."],
    confidence: "low",
    sources: [{ label: "The Street Book (Henry Moscow), batch 5" }],
    coordinates: [
      [-74.0052, 40.7308],
      [-74.0042, 40.7312],
      [-74.0031, 40.7316],
    ],
  },
  {
    id: "doyers-street",
    corridor: "Chinatown Legacy Streets",
    currentName: "Doyers Street",
    segmentLabel: "Curved Chinatown alley corridor",
    bounds: "Chinatown",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Anthony H. Doyer, a distiller who established a tea garden in Rutgers-farm lands; his 1809 house helped seed local lore.",
    timeline: ["Late 18th century: Tea-garden period.", "1809: House at No. 3 linked to local legend."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 5" }],
    coordinates: [
      [-73.9985, 40.7145],
      [-73.9974, 40.7138],
      [-73.9966, 40.713],
    ],
  },
  {
    id: "duane-street",
    corridor: "Civic Center / Tribeca Historic Streets",
    currentName: "Duane Street",
    segmentLabel: "Civic Center to Tribeca crosstown",
    bounds: "Lower Manhattan",
    altNames: [],
    formerNames: [],
    origin:
      "Named for James Duane, first post-evacuation mayor of New York (after 1783), later appointed a U.S. District Court judge by Washington.",
    timeline: ["1783: Duane becomes mayor after British evacuation.", "Post-Revolution: Federal judicial appointment."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 5" }],
    coordinates: [
      [-74.0108, 40.7164],
      [-74.0076, 40.7167],
      [-74.0045, 40.717],
      [-74.0015, 40.7173],
    ],
  },
  {
    id: "duffy-square",
    corridor: "Times Square Memorial Spaces",
    currentName: "Duffy Square",
    segmentLabel: "Times Square north triangle",
    bounds: "Times Square area",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Father Francis P. Duffy, military chaplain of the 165th U.S. Infantry and decorated veteran of multiple conflicts; memorialized after his 1932 death.",
    timeline: ["Early 20th century: Chaplaincy and military service.", "1932: Duffy dies; memorial naming follows."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 5" }],
    coordinates: [
      [-73.9859, 40.7593],
      [-73.9852, 40.7598],
      [-73.9845, 40.7602],
      [-73.9859, 40.7593],
    ],
  },
  {
    id: "duke-ellington-boulevard",
    corridor: "Upper West Side Commemorative Streets",
    currentName: "Duke Ellington Boulevard",
    segmentLabel: "W 106th ceremonial segment",
    bounds: "Riverside Drive to Central Park West",
    altNames: ["West 106th Street"],
    formerNames: ["West 106th Street"],
    origin:
      "Renamed in 1977 for Duke Ellington (Edward Kennedy Ellington), composer and bandleader associated with the street and neighborhood.",
    timeline: ["1977: Street co-named for Duke Ellington."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 5" }],
    coordinates: [
      [-73.9774, 40.8008],
      [-73.9713, 40.8008],
      [-73.9652, 40.8008],
      [-73.959, 40.8008],
    ],
  },
  {
    id: "dutch-street",
    corridor: "Financial District Colonial Streets",
    currentName: "Dutch Street",
    segmentLabel: "Historic FiDi side street",
    bounds: "Lower Manhattan",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Dutch founders of the city; laid out before 1730 and formally graded in 1789.",
    timeline: ["Pre-1730: Street laid out.", "1789: Grading and formalization."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 5" }],
    coordinates: [
      [-74.008, 40.7103],
      [-74.0068, 40.7106],
      [-74.0056, 40.7109],
    ],
  },
  {
    id: "dyckman-street",
    corridor: "Inwood Historic Arterials",
    currentName: "Dyckman Street",
    segmentLabel: "Inwood cross-island corridor",
    bounds: "Upper Manhattan (Inwood)",
    altNames: [],
    formerNames: [],
    origin:
      "Named for the Dyckman family, major landholders in upper Manhattan whose holdings reached major scale by the Civil War era.",
    timeline: ["Mid-17th century: Earliest Dyckman arrival in New Amsterdam context.", "Civil War era: Very large family farm holdings."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 5" }],
    coordinates: [
      [-73.9404, 40.8653],
      [-73.9336, 40.8663],
      [-73.9266, 40.8674],
      [-73.9195, 40.8684],
    ],
  },
  {
    id: "dyer-avenue",
    corridor: "Hudson Yards / Midtown West Streets",
    currentName: "Dyer Avenue",
    segmentLabel: "Midtown west connector",
    bounds: "Historically between Liberty and Cortlandt naming context (book source); modern Midtown segments",
    altNames: [],
    formerNames: [],
    origin:
      "Likely named for William Dyre, appointed mayor in 1680 and known for controversial tax and customs policies.",
    timeline: ["1680s: William Dyre mayoral period."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), batch 5" }],
    coordinates: [
      [-73.9955, 40.7534],
      [-73.9947, 40.7588],
      [-73.9938, 40.7642],
    ],
  },
];

export const CONFIDENCE_COLORS = {
  high: "#34d399",
  medium: "#f59e0b",
  low: "#f87171",
};
