export const MANHATTAN_ISLAND = {
  type: "Feature",
  properties: { name: "Manhattan" },
  geometry: {
    type: "Polygon",
    coordinates: [
      [
        [-74.0196, 40.7002],
        [-74.0178, 40.7098],
        [-74.0149, 40.7198],
        [-74.0127, 40.7302],
        [-74.0105, 40.7406],
        [-74.0084, 40.7509],
        [-74.0061, 40.7615],
        [-74.0028, 40.7724],
        [-73.9988, 40.7835],
        [-73.9938, 40.7943],
        [-73.9883, 40.8047],
        [-73.9819, 40.8155],
        [-73.9736, 40.8288],
        [-73.9657, 40.8422],
        [-73.9583, 40.8554],
        [-73.9519, 40.8706],
        [-73.9412, 40.8778],
        [-73.9312, 40.8734],
        [-73.9362, 40.8598],
        [-73.9414, 40.8465],
        [-73.9468, 40.8334],
        [-73.9526, 40.8202],
        [-73.9588, 40.8068],
        [-73.9653, 40.7936],
        [-73.9709, 40.7802],
        [-73.9756, 40.7663],
        [-73.9799, 40.7523],
        [-73.9846, 40.7384],
        [-73.9898, 40.7241],
        [-73.9961, 40.7113],
        [-74.0039, 40.7026],
        [-74.0126, 40.6996],
        [-74.0196, 40.7002],
      ],
    ],
  },
};

export const MANHATTAN_STREET_SEGMENTS = [
  {
    id: "broadway-financial-district",
    corridor: "Broadway Corridor",
    currentName: "Broadway",
    segmentLabel: "Battery to City Hall",
    bounds: "Bowling Green to City Hall Park",
    altNames: ["The Great White Way (nickname, especially in Midtown)"],
    formerNames: ["Breede weg (Dutch, \"broad road\")"],
    origin:
      "Broadway follows a pre-colonial Lenape path. Dutch settlers called it Breede weg, which later became Broadway in English.",
    timeline: [
      "Pre-1600s: Native path used across lower Manhattan.",
      "1600s: Dutch colonists document it as Breede weg.",
      "1700s onward: Anglicized as Broadway.",
    ],
    confidence: "high",
    sources: [
      { label: "NYC Parks - Broadway Malls", url: "https://www.nycgovparks.org/parks/broadway-malls/history" },
      { label: "Wikipedia - Broadway (Manhattan)", url: "https://en.wikipedia.org/wiki/Broadway_(Manhattan)" },
    ],
    coordinates: [
      [-74.0121, 40.7047],
      [-74.0088, 40.7125],
      [-74.0056, 40.7212],
      [-74.0019, 40.7301],
    ],
  },
  {
    id: "broadway-midtown",
    corridor: "Broadway Corridor",
    currentName: "Broadway",
    segmentLabel: "Union Square to Columbus Circle",
    bounds: "Union Square to Columbus Circle",
    altNames: ["The Great White Way (theater district nickname)"],
    formerNames: [],
    origin:
      "The Midtown segment became globally known for its theater corridor, earning the nickname 'The Great White Way' due to bright electric signs.",
    timeline: [
      "Late 1800s to early 1900s: Theater concentration accelerates.",
      "Early 1900s: Nickname 'The Great White Way' popularized.",
    ],
    confidence: "medium",
    sources: [
      { label: "Britannica - Broadway", url: "https://www.britannica.com/topic/Broadway-theatre-district-New-York-City-New-York" },
      { label: "Wikipedia - Broadway Theater", url: "https://en.wikipedia.org/wiki/Broadway_theatre" },
    ],
    coordinates: [
      [-73.9901, 40.7363],
      [-73.9868, 40.7451],
      [-73.983, 40.7556],
      [-73.98, 40.7658],
      [-73.9776, 40.7746],
    ],
  },
  {
    id: "sixth-ave-village",
    corridor: "Avenue of the Americas / 6th Ave",
    currentName: "Avenue of the Americas",
    segmentLabel: "SoHo / Greenwich Village section",
    bounds: "Canal St to 14th St",
    altNames: ["Sixth Avenue", "6th Ave"],
    formerNames: [],
    origin:
      "The avenue was officially renamed Avenue of the Americas in 1945 to promote Pan-American unity, but many New Yorkers still use 'Sixth Avenue' in speech.",
    timeline: [
      "Before 1945: Sixth Avenue.",
      "1945: Officially renamed Avenue of the Americas.",
      "Present: Dual usage remains common.",
    ],
    confidence: "high",
    sources: [
      { label: "NYC Department of City Planning references", url: "https://www.nyc.gov/site/planning/" },
      { label: "Wikipedia - Sixth Avenue", url: "https://en.wikipedia.org/wiki/Sixth_Avenue" },
    ],
    coordinates: [
      [-74.0095, 40.7211],
      [-74.0066, 40.7293],
      [-74.0023, 40.7382],
    ],
  },
  {
    id: "sixth-ave-midtown",
    corridor: "Avenue of the Americas / 6th Ave",
    currentName: "Avenue of the Americas",
    segmentLabel: "Midtown section",
    bounds: "14th St to Central Park South",
    altNames: ["Sixth Avenue", "6th Ave"],
    formerNames: [],
    origin:
      "Even on official maps and signs, the avenue often displays both naming traditions: ceremonial naming plus numeric avenue identity.",
    timeline: [
      "1945 onward: Avenue of the Americas (official).",
      "Continuous colloquial use: Sixth Avenue.",
    ],
    confidence: "medium",
    sources: [
      { label: "NYC signage practices overview", url: "https://www.nyc.gov/" },
      { label: "Wikipedia - Sixth Avenue", url: "https://en.wikipedia.org/wiki/Sixth_Avenue" },
    ],
    coordinates: [
      [-74.0023, 40.7382],
      [-73.9972, 40.7484],
      [-73.9933, 40.759],
      [-73.9894, 40.7697],
      [-73.9858, 40.7802],
    ],
  },
  {
    id: "bowery-lower",
    corridor: "Bowery / 4th Ave / Park Ave Corridor",
    currentName: "Bowery",
    segmentLabel: "Chatham Square to Cooper Square",
    bounds: "Chatham Square to Cooper Square",
    altNames: [],
    formerNames: ["Bouwerij road (Dutch farm road root)"],
    origin:
      "Bowery derives from Dutch 'bouwerij' (farm). The route linked colonial farms north of the original settlement.",
    timeline: [
      "1600s: Farm road associated with Dutch bouwerij lands.",
      "1700s onward: Name evolves to Bowery.",
    ],
    confidence: "high",
    sources: [
      { label: "Wikipedia - Bowery", url: "https://en.wikipedia.org/wiki/Bowery" },
      { label: "NYC neighborhood history resources", url: "https://www.nyc.gov/" },
    ],
    coordinates: [
      [-73.9967, 40.7114],
      [-73.9939, 40.7182],
      [-73.9908, 40.7249],
      [-73.9878, 40.7296],
    ],
  },
  {
    id: "fourth-ave-union",
    corridor: "Bowery / 4th Ave / Park Ave Corridor",
    currentName: "Fourth Avenue",
    segmentLabel: "Cooper Square to Union Square",
    bounds: "Astor Place area to Union Square",
    altNames: [],
    formerNames: [],
    origin:
      "This short section carries the numbered avenue scheme before the same northbound alignment transitions into Park Avenue South.",
    timeline: [
      "19th century grid era: Standard numbered avenue naming.",
      "At 14th Street: Name changes to Park Avenue South.",
    ],
    confidence: "medium",
    sources: [
      { label: "Wikipedia - Fourth Avenue (Manhattan)", url: "https://en.wikipedia.org/wiki/Fourth_Avenue_(Manhattan)" },
    ],
    coordinates: [
      [-73.9878, 40.7296],
      [-73.9851, 40.7361],
      [-73.9826, 40.7422],
    ],
  },
  {
    id: "park-ave-south",
    corridor: "Bowery / 4th Ave / Park Ave Corridor",
    currentName: "Park Avenue South",
    segmentLabel: "Union Square to Grand Central area",
    bounds: "14th St to 32nd St",
    altNames: ["Fourth Avenue (historic continuity)"],
    formerNames: [],
    origin:
      "As the corridor moved uptown and urban design changed, this stretch adopted the Park Avenue South name while remaining part of the same traffic spine.",
    timeline: [
      "After 14th Street: corridor renamed Park Avenue South.",
      "Northbound continuity persists into Park Avenue.",
    ],
    confidence: "medium",
    sources: [
      { label: "Wikipedia - Park Avenue", url: "https://en.wikipedia.org/wiki/Park_Avenue" },
    ],
    coordinates: [
      [-73.9826, 40.7422],
      [-73.98, 40.7487],
      [-73.9777, 40.7553],
      [-73.9758, 40.7617],
      [-73.9744, 40.7685],
    ],
  },
  {
    id: "park-ave-upper",
    corridor: "Bowery / 4th Ave / Park Ave Corridor",
    currentName: "Park Avenue",
    segmentLabel: "Midtown to Upper Manhattan",
    bounds: "32nd St to Harlem River area",
    altNames: [],
    formerNames: ["Fourth Avenue (historic name, earlier period)"],
    origin:
      "The boulevard became associated with landscaped medians and rail improvements, helping cement the Park Avenue identity.",
    timeline: [
      "19th century: Fourth Avenue naming in use.",
      "Late 19th century onward: Park Avenue identity solidifies.",
    ],
    confidence: "medium",
    sources: [
      { label: "Wikipedia - Park Avenue", url: "https://en.wikipedia.org/wiki/Park_Avenue" },
      { label: "NYC Landmarks and neighborhood histories", url: "https://www.nyc.gov/site/lpc/" },
    ],
    coordinates: [
      [-73.9744, 40.7685],
      [-73.9728, 40.7765],
      [-73.9712, 40.7859],
      [-73.9695, 40.7967],
      [-73.9668, 40.8092],
      [-73.9639, 40.8226],
      [-73.9609, 40.8362],
      [-73.9579, 40.8502],
      [-73.9547, 40.8638],
    ],
  },
  {
    id: "malcolmx-lenox",
    corridor: "Lenox / Malcolm X Corridor",
    currentName: "Malcolm X Boulevard",
    segmentLabel: "Central Harlem section",
    bounds: "110th St to 147th St corridor",
    altNames: ["Lenox Avenue"],
    formerNames: ["Lenox Avenue (still used for parts and in older references)"],
    origin:
      "Portions were ceremonially renamed Malcolm X Boulevard in the late 20th century, reflecting neighborhood identity and civil rights memory.",
    timeline: [
      "Earlier usage: Lenox Avenue.",
      "1987: Malcolm X Boulevard naming adopted for significant stretches.",
      "Present: both names appear depending on segment/signage context.",
    ],
    confidence: "high",
    sources: [
      { label: "Wikipedia - Malcolm X Boulevard", url: "https://en.wikipedia.org/wiki/Malcolm_X_Boulevard" },
      { label: "Wikipedia - Lenox Avenue", url: "https://en.wikipedia.org/wiki/Lenox_Avenue" },
    ],
    coordinates: [
      [-73.9504, 40.7935],
      [-73.9488, 40.8024],
      [-73.947, 40.8117],
      [-73.9451, 40.8214],
      [-73.9433, 40.8313],
      [-73.9415, 40.8413],
      [-73.9398, 40.8516],
      [-73.9382, 40.8615],
    ],
  },
  {
    id: "adam-clayton-powell",
    corridor: "Seventh Avenue Corridor",
    currentName: "Adam Clayton Powell Jr. Boulevard",
    segmentLabel: "Harlem segment (co-named Seventh Avenue)",
    bounds: "Harlem, north of Central Park",
    altNames: ["Seventh Avenue"],
    formerNames: ["Seventh Avenue (Harlem portion)"],
    origin:
      "Named for Adam Clayton Powell Jr., the 11-term Congressman from Harlem and pastor of Abyssinian Baptist Church. A major civil rights leader, he was first elected to Congress in 1944. The Harlem stretch of Seventh Avenue was named for him shortly after his death in 1972.",
    timeline: [
      "Original avenue grid: Seventh Avenue.",
      "1944: Powell elected to Congress.",
      "1972: Boulevard naming adopted after Powell's death.",
    ],
    confidence: "high",
    sources: [
      { label: "The Street Book (Henry Moscow), p. 24" },
      { label: "Wikipedia - Adam Clayton Powell Jr. Boulevard", url: "https://en.wikipedia.org/wiki/Adam_Clayton_Powell_Jr._Boulevard" },
    ],
    coordinates: [
      [-73.9803, 40.7536],
      [-73.9771, 40.7636],
      [-73.9737, 40.7741],
      [-73.9699, 40.7848],
      [-73.9658, 40.7958],
      [-73.9614, 40.8069],
      [-73.9566, 40.8182],
      [-73.9515, 40.8294],
      [-73.946, 40.8408],
      [-73.9405, 40.8521],
    ],
  },
  {
    id: "fdr-drive",
    corridor: "East Side Arterial",
    currentName: "FDR Drive",
    segmentLabel: "East River waterfront",
    bounds: "Battery Park area to Harlem River",
    altNames: ["East River Drive (historic name)"],
    formerNames: ["East River Drive"],
    origin:
      "Originally known as East River Drive, the route was later renamed for President Franklin D. Roosevelt.",
    timeline: [
      "Mid-20th century construction period: East River Drive.",
      "Later renamed FDR Drive.",
    ],
    confidence: "high",
    sources: [
      { label: "Wikipedia - FDR Drive", url: "https://en.wikipedia.org/wiki/FDR_Drive" },
      { label: "NYC DOT references", url: "https://www.nyc.gov/html/dot/" },
    ],
    coordinates: [
      [-73.9722, 40.7042],
      [-73.9719, 40.7151],
      [-73.9708, 40.7266],
      [-73.9691, 40.7384],
      [-73.9666, 40.7502],
      [-73.9636, 40.7626],
      [-73.9601, 40.7746],
      [-73.9563, 40.7871],
      [-73.9522, 40.7995],
      [-73.9478, 40.8126],
      [-73.9433, 40.8265],
      [-73.9382, 40.8412],
      [-73.9328, 40.8562],
      [-73.9279, 40.8694],
    ],
  },
  {
    id: "west-side-highway",
    corridor: "West Side Arterial",
    currentName: "West Side Highway",
    segmentLabel: "Hudson River waterfront",
    bounds: "Battery Place to upper Manhattan",
    altNames: ["Joe DiMaggio Highway", "Route 9A (parts)"],
    formerNames: ["Miller Highway (older elevated sections)"],
    origin:
      "The corridor has carried multiple names over time, including commemorative and route-designation labels layered onto the same north-south waterfront path.",
    timeline: [
      "Earlier era: Miller Highway for elevated segments.",
      "Modern era: West Side Highway.",
      "Commemorative co-name: Joe DiMaggio Highway.",
    ],
    confidence: "medium",
    sources: [
      { label: "Wikipedia - West Side Highway", url: "https://en.wikipedia.org/wiki/West_Side_Highway" },
      { label: "NYC DOT arterial history resources", url: "https://www.nyc.gov/html/dot/" },
    ],
    coordinates: [
      [-74.0159, 40.7047],
      [-74.0144, 40.716],
      [-74.0128, 40.7276],
      [-74.0114, 40.7396],
      [-74.0098, 40.7518],
      [-74.0083, 40.7643],
      [-74.0068, 40.7765],
      [-74.0052, 40.7891],
      [-74.0036, 40.8022],
      [-74.0016, 40.8157],
      [-73.9994, 40.8299],
      [-73.9969, 40.8449],
      [-73.9942, 40.8598],
      [-73.9916, 40.8726],
    ],
  },
  {
    id: "canal-street",
    corridor: "Historic Waterway Streets",
    currentName: "Canal Street",
    segmentLabel: "Lower Manhattan crosstown",
    bounds: "Hudson-side approaches to East Side approaches",
    altNames: [],
    formerNames: [],
    origin:
      "Canal Street traces the line of a former canal built over the old Collect Pond drainage corridor in the early 19th century.",
    timeline: [
      "Early 1800s: Canal built to drain the Collect Pond area.",
      "Later: Waterway filled, roadway remains as Canal Street.",
    ],
    confidence: "high",
    sources: [
      { label: "Wikipedia - Canal Street (Manhattan)", url: "https://en.wikipedia.org/wiki/Canal_Street_(Manhattan)" },
      { label: "NYC historical maps references", url: "https://www.nypl.org/" },
    ],
    coordinates: [
      [-74.0107, 40.7186],
      [-74.0021, 40.7186],
      [-73.9935, 40.7187],
      [-73.9852, 40.7187],
      [-73.9767, 40.7188],
    ],
  },
  {
    id: "houston-street",
    corridor: "Historic Waterway Streets",
    currentName: "Houston Street",
    segmentLabel: "West Village to Lower East Side",
    bounds: "West Side to East Side crosstown corridor",
    altNames: ["Pronounced 'HOW-ston' (not like Houston, Texas)"],
    formerNames: [],
    origin:
      "Named after William Houstoun (a Georgia statesman), producing the local pronunciation 'HOW-ston' that differs from Houston, Texas.",
    timeline: [
      "Early naming: after William Houstoun family context.",
      "Present: distinctive NYC pronunciation remains in common use.",
    ],
    confidence: "medium",
    sources: [
      { label: "Wikipedia - Houston Street", url: "https://en.wikipedia.org/wiki/Houston_Street" },
      { label: "NYC historical pronunciation notes", url: "https://www.nypl.org/" },
    ],
    coordinates: [
      [-74.0085, 40.7287],
      [-73.9994, 40.7288],
      [-73.9903, 40.7288],
      [-73.9812, 40.7289],
      [-73.9721, 40.729],
    ],
  },
  {
    id: "wall-street",
    corridor: "Colonial-Era Streets",
    currentName: "Wall Street",
    segmentLabel: "Financial District core",
    bounds: "Broadway to South Street area",
    altNames: ["The Street (financial shorthand)"],
    formerNames: [],
    origin:
      "Named for the defensive wall built by Dutch colonists along the northern edge of New Amsterdam in the 17th century.",
    timeline: [
      "1650s: Defensive wall established.",
      "Later: Wall removed, street name remains.",
      "Modern era: Global financial symbolism.",
    ],
    confidence: "high",
    sources: [
      { label: "Federal Reserve history notes", url: "https://www.federalreservehistory.org/" },
      { label: "Wikipedia - Wall Street", url: "https://en.wikipedia.org/wiki/Wall_Street" },
    ],
    coordinates: [
      [-74.0103, 40.7073],
      [-74.0063, 40.7075],
      [-74.0025, 40.7077],
      [-73.9989, 40.7078],
    ],
  },
  {
    id: "abingdon-square",
    corridor: "Greenwich Village Squares",
    currentName: "Abingdon Square",
    segmentLabel: "Historic Village square block",
    bounds: "Bounded by Charles, Perry, Bleecker, and Tenth Streets",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Charlotte Warren, daughter of Admiral Sir Peter Warren, who married the Earl of Abingdon. Although many British-linked names were changed in 1794, Abingdon Square's name was retained.",
    timeline: ["1744: Warren land purchase.", "1794: Name retained during broader renaming efforts."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 24" }],
    coordinates: [
      [-74.0053, 40.7364],
      [-74.0038, 40.7368],
      [-74.0028, 40.7357],
      [-74.0043, 40.7352],
      [-74.0053, 40.7364],
    ],
  },
  {
    id: "academy-street",
    corridor: "Inwood Streets",
    currentName: "Academy Street",
    segmentLabel: "Dyckman / Inwood section",
    bounds: "Dyckman Street area (Inwood)",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Public School 52, a Tudor-style school building that once occupied a full block in the Inwood area before being demolished in 1957.",
    timeline: ["Pre-1957: Name tied to P.S. 52 context."],
    confidence: "medium",
    sources: [{ label: "The Street Book (Henry Moscow), p. 24" }],
    coordinates: [
      [-73.9315, 40.8673],
      [-73.9299, 40.868],
      [-73.9276, 40.869],
    ],
  },
  {
    id: "admiral-george-dewey-promenade",
    corridor: "Battery Park Waterfront",
    currentName: "Admiral George Dewey Promenade",
    segmentLabel: "Battery waterfront walk",
    bounds: "Harbor / Battery Park edge",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Admiral George Dewey, whose Manila Bay victory in 1898 made him a national hero. The promenade naming came later, in 1965.",
    timeline: ["1899: Hero's welcome in New York.", "1965: Promenade named in his honor."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 25" }],
    coordinates: [
      [-74.0175, 40.7044],
      [-74.0168, 40.7048],
      [-74.0158, 40.7051],
      [-74.0148, 40.7052],
    ],
  },
  {
    id: "albany-street",
    corridor: "Lower Manhattan Historic Streets",
    currentName: "Albany Street",
    segmentLabel: "Lower Manhattan segment",
    bounds: "Hudson River side toward Broadway (planned extension)",
    altNames: [],
    formerNames: [],
    origin:
      "Named for a Hudson-side pier built in 1797 serving New York-Albany traffic. A long 19th-century effort to extend the street through Trinity Churchyard was never carried out.",
    timeline: ["1797: Street tied to Albany-run pier.", "1850s: Extension controversy ends without completion."],
    confidence: "medium",
    sources: [{ label: "The Street Book (Henry Moscow), p. 25" }],
    coordinates: [
      [-74.0154, 40.7094],
      [-74.0128, 40.7095],
      [-74.0103, 40.7097],
    ],
  },
  {
    id: "alexander-hamilton-square",
    corridor: "Hamilton Heights Landmarks",
    currentName: "Alexander Hamilton Square",
    segmentLabel: "Near The Grange",
    bounds: "Hamilton Heights / St. Nicholas Park area",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Alexander Hamilton, Revolutionary officer and first U.S. Treasury Secretary. The square is associated with the area around his historic home, The Grange.",
    timeline: ["1800s onward: Square naming associated with Hamilton legacy."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 25" }],
    coordinates: [
      [-73.9498, 40.8226],
      [-73.9487, 40.8231],
      [-73.9476, 40.8235],
    ],
  },
  {
    id: "allen-street",
    corridor: "Lower East Side Corridors",
    currentName: "Allen Street",
    segmentLabel: "Lower East Side segment",
    bounds: "Lower East Side",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Captain William Henry Allen, a young U.S. Navy commander of the War of 1812 who died in action in 1813.",
    timeline: ["1813: Street naming linked to Captain Allen's death and public tribute."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 26" }],
    coordinates: [
      [-73.9924, 40.7149],
      [-73.9918, 40.7195],
      [-73.9911, 40.7246],
      [-73.9904, 40.7297],
    ],
  },
  {
    id: "amsterdam-avenue",
    corridor: "West Side Avenues",
    currentName: "Amsterdam Avenue",
    segmentLabel: "Above 59th Street",
    bounds: "Above 59th Street",
    altNames: ["Tenth Avenue (historic continuity)"],
    formerNames: ["Tenth Avenue (above 59th Street)"],
    origin:
      "Renamed in 1890 from the northern portion of Tenth Avenue. The name references Amsterdam and New York's Dutch settlement history; proponents also argued the change would improve neighborhood appeal and property values.",
    timeline: ["Before 1890: Tenth Avenue above 59th Street.", "1890: Officially renamed Amsterdam Avenue."],
    confidence: "high",
    sources: [{ label: "The Street Book (Henry Moscow), p. 26" }],
    coordinates: [
      [-73.9882, 40.7681],
      [-73.9845, 40.7795],
      [-73.9806, 40.7914],
      [-73.9766, 40.8036],
      [-73.9725, 40.8159],
      [-73.9685, 40.8284],
      [-73.9649, 40.8404],
      [-73.9612, 40.8529],
    ],
  },
  {
    id: "ann-street",
    corridor: "Lower Manhattan Historic Streets",
    currentName: "Ann Street",
    segmentLabel: "Downtown short street",
    bounds: "Downtown Manhattan",
    altNames: [],
    formerNames: [],
    origin:
      "Named for Ann White, wife of merchant and developer Captain Thomas White, who subdivided land in the old governor's garden area.",
    timeline: ["18th century: Street established and named for Ann White."],
    confidence: "medium",
    sources: [{ label: "The Street Book (Henry Moscow), p. 26" }],
    coordinates: [
      [-74.0082, 40.7105],
      [-74.0066, 40.7108],
      [-74.0049, 40.711],
    ],
  },
];

export const CONFIDENCE_COLORS = {
  high: "#34d399",
  medium: "#f59e0b",
  low: "#f87171",
};
